In [2]:
# Importing the Numpy library with an alias 'np' to use in all the numpy problems.
import numpy as np

1. Write a Numpy program to get Numpy version and build configuration.

In [3]:
# np.__version__ : this will give us the version installed in our system
print(np.__version__)

# np.show_config() : this method is used to get the configuration of numpy
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Madhavz/anaconda3/Library/include
    lib directory: C:/Users/Madhavz/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host

2. Write a NumPy program to get help with the add function.

In [4]:
# np.info(argument) : this method is used to get information about the argument that we pass to it
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

3. Write a NumPy program to test whether none of the elements of a given array are zero.

In [5]:
# np.array(iterable) : this method is used to create an array of elements passed in the iterable
arr1 = np.array([1, 2, 3, 4])

# np.all(array) : this method returns true if all the elements in the array are non-zero else returns false.
print(np.all(arr1))

# take another array 'arr2' containing elements 0, 1, 2, and 3
arr2 = np.array([0, 1, 2, 3])

print(np.all(arr2))

True
False


4. Write a Numpy program to test if any of the elements of a given array are non-zero.

In [6]:
# Creating an array 'arr1' containing elements 1, 2, 3, and 4
arr1 = np.array([1, 2, 3, 4])

# np.any(array) : this method returns true if any element in the arrray is non-zero else returns false.
print(np.any(arr1))

# another array with 4 elements as zero
print(np.any([0, 0, 0, 0]))

True
False


5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a number).

In [7]:
# create an array containing 12, 22, NaN and Infinity
# np.nan: it produces not a number (NaN)
# np.inf: it produces infinity 
arr = np.array([12, 22, np.nan, np.inf])

# np.isfinite(array) : Returns an array containing true for the corresponding element if the element is finite else false.
print(np.isfinite(arr))

[ True  True False False]


6. Write a NumPy program to test elements-wise for positive or negative infinity. 

In [8]:
# creating an array containing positive infinity, negative infinity and some integers
# np.inf: it produces infinity 
arr = np.array([np.inf, -np.inf, 0, 12, 22, np.inf])

# np.isposinf(array) : this method checks for positive infinities in the array and returns true for it if found else false as an array
print('Positive Infinity Checking: ', np.isposinf(arr))

# np.isneginf(array) : this method checks for negative infinities in the array and returns true for it if found else false as an array
print('Negative Infinity Checking: ', np.isneginf(arr))

Positive Infinity Checking:  [ True False False False False  True]
Negative Infinity Checking:  [False  True False False False False]


7. Write a NumPy program to test element-wise for NaN of a given array.

In [9]:
# creating an array containing NaN and some integers
# np.nan: it produces not a number (NaN)
arr = np.array([np.nan, 22, 12, np.nan, np.inf])

# np.isnan(array) : this method checks for NaN and returns a boolean array
print('Original Array: ', arr)
print('NaN Checking: ', np.isnan(arr))

Original Array:  [nan 22. 12. nan inf]
NaN Checking:  [ True False False  True False]


8. Write a NumPy program to test element-wise for complex numbers, real numbers in a given array. Also test if a given number is of a scalar type or not. 

In [10]:
# create an array with elements containing complex, real and integer numbers.
arr = np.array([complex(12, 22), 22, 12, complex(22, 12)])

# np.iscomplex(array) : This method checks for complex number elements in an array. Return a boolean array.
# np.isreal(array) : This method checks for real number elements in an array. Return a boolean array.
# np.isscalar(array) : This method checks a number and returns true if it is a number else false.
print('Original Array: ', arr)
print('Complex Number Checking: ', np.iscomplex(arr))
print('Real Number Checking: ', np.isreal(arr))
print('Scalars Checking: ', np.isscalar(25.5))

Original Array:  [12.+22.j 22. +0.j 12. +0.j 22.+12.j]
Complex Number Checking:  [ True False False  True]
Real Number Checking:  [False  True  True False]
Scalars Checking:  True


9. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

In [11]:
# create two identical arrays with four elements each
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([1, 2, 3, 4])

# np.allclose(array1, array2) : This method returns True if the specified arrays are element-wise equal within a tolerance.
print('Identical Arrays: ',np.allclose(arr1, arr2))

# lets go with multiple type of arrays with different tolerance: 
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))

print('Equal arrays with NaN: ',np.allclose([1.0, np.nan], [1.0, np.nan]))
print('Equal arrays with NaN, with "equal_nan=True" argument: ', np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True)) 

Identical Arrays:  True
False
True
False
Equal arrays with NaN:  False
Equal arrays with NaN, with "equal_nan=True" argument:  True


10. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [12]:
# create two arrays of same size with different elements
arr1 = np.array([12, 22, 32, 34, 55, 838])
arr2 = np.array([22, 34, 35, 235, 44, 893])

# np.greater(array1, array2) is same as array1 > array2 
# np.greater_equal(array1, array2) is same as array1 >= array2
# np.less(array1, array2) is same as array1 < array2
# np.less_equal(array1, array2) is same as array1 <= array2

print('Array 1: ', arr1)
print('Array 2: ', arr2)
print('greater Array: ', np.greater(arr1, arr2))
print('greater_equal: ', np.greater_equal(arr1, arr2))
print('less: ', np.less(arr1, arr2))
print('less_equal: ', np.less_equal(arr1, arr2))

Array 1:  [ 12  22  32  34  55 838]
Array 2:  [ 22  34  35 235  44 893]
greater Array:  [False False False False  True False]
greater_equal:  [False False False False  True False]
less:  [ True  True  True  True False  True]
less_equal:  [ True  True  True  True False  True]


11. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [13]:
# create two arrays of same size with different elements
arr1 = np.array([12, 22, 32, 34, 22, 838])
arr2 = np.array([12, 34, 32, 235, 22, 893])

# np.equal(array1, arra2) is same as array1 == array2
# np.allclose(array1, array2) : This method checks if two arrays are equal with some tolerance.
print('Array 1: ', arr1)
print('Array 2: ', arr2)
print('equal: ',np.equal(arr1, arr2))
print('equal with tolerance: ', np.allclose(arr1, arr2))

Array 1:  [ 12  22  32  34  22 838]
Array 2:  [ 12  34  32 235  22 893]
equal:  [ True False  True False  True False]
equal with tolerance:  False


12. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [14]:
# Create an array with elements as 1, 7, 13 and 105
arr = np.array([1,7,13,105])

# array.size : this gives the number of elements in the array
# array.itemsize : this gives the size of an element in the array
print('Size of the array: ', arr.size * arr.itemsize)

Size of the array:  16


13. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives

In [15]:
# create an array of 10 zeros
# np.zeros(shape) : This method is used to create an array of zeros of specified shape 
print('Array of zeros: ', np.zeros(10))

# np.ones(shape) : This method is used to create an array of ones of specified shape
print('Array of ones: ', np.ones(10))

# Array of 10 fives
print('Array of fives: ', np.ones(10) * 5)

Array of zeros:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of ones:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of fives:  [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


14. Write a NumPy program to create an array of integers from 30 to 70.

In [16]:
# np.arange(start, stop, step) : This method is used create an array starting from the 'start' argument to 'stop' argument with 'step' as mentioned
print('Array from 30 to 70: ', np.arange(30, 70))

Array from 30 to 70:  [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


15. Write a NumPy program to create an array of all even integers from 30 to 70.

In [17]:
# when we pass step = 2 automatically even integers become the array
print('Even Integer Array from 30 to 70: ', np.arange(30, 70, 2))

Even Integer Array from 30 to 70:  [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


16. Write a NumPy program to create a 3x3 identity matrix.

In [18]:
# np.identity(size) : Create an identity matrix of size * size
identity_matrix = np.identity(3)
print('Identity Matrix: ', identity_matrix)

Identity Matrix:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


17. Write a NumPy program to generate a random number between 0 and 1.

In [19]:
# np.random.rand(n) : This method will return n random numbers between 0 and 1, default n = 1
print('Random Number between 0 and 1: ', np.random.rand())

Random Number between 0 and 1:  0.8517551952801795


18. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [20]:
# np.random.normal(mean, std, size) : This method generates an of specified size from a normal distribution with specified mean and standard deviation
print('Random Numbers from a Normal Dist: ', np.random.normal(0, 1, 15))

Random Numbers from a Normal Dist:  [ 0.70499951  1.66839763  1.72660481 -0.5220189   0.08080955  1.66791143
  0.06157087  0.91116444 -0.42145854 -0.72732239  0.1785792  -1.84818704
  0.76170383 -0.85255384 -0.73314773]


19. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [21]:
# Vector : a 1 dimensional array is called Vector.
arr = np.arange(15, 55)[1:-1]
print('Vector ranging from 15 to 55: ', arr)

Vector ranging from 15 to 55:  [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


20.  Write a NumPy program to create a 3X4 array and iterate over it.

In [22]:
# array.reshape(shape) : This method is used to reshape an array to the specified shape.
arr = np.arange(1, 13).reshape((3,4))

# np.nditer(array) : This method will iterate over all the elements of the specified array.
for i in np.nditer(arr):
    print(i, end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 

21. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [23]:
# Vector : a 1 dimensional array is called a vector
# np.linspace(start, stop, size, endpint=True) : This method returns an array of specified 'size' from range 'start' to 'stop'. if endpoint=True, the 'stop' is last element. By default endpoint=True
print('Vector between 5 and 50: ', np.linspace(5, 50, 10, endpoint=False))

Vector between 5 and 50:  [ 5.   9.5 14.  18.5 23.  27.5 32.  36.5 41.  45.5]


22. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [24]:
# Vector with values from 0 to 20.
arr = np.arange(21)
print('Original Vector: ', arr)

# we can go with conditional and arithmetic operations within an array
# this filters elements greater than 8 and less than 16 which are multiplied with -1
arr[(arr > 8) & (arr < 16)] *= -1
print('Changed Vector: ', arr)

Original Vector:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Changed Vector:  [  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


23. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [25]:
# np.random.randint(start, stop, size) : This method returns a vector of specified size with integers ranging from start to stop
print('Arbitrary Integers from 0 to 10: ', np.random.randint(0, 11, 5))

Arbitrary Integers from 0 to 10:  [4 4 9 9 1]


24. Write a NumPy program to multiply the values of two given vectors.

In [26]:
# multiplication between values of two given vectors are done with '*' (asterisk)
arr1 = np.arange(1, 10)
arr2 = np.arange(11, 20)
print('Array1: ', arr1)
print('Array2: ', arr2)
print('Product of 2 Vectors: ', arr1*arr2)

Array1:  [1 2 3 4 5 6 7 8 9]
Array2:  [11 12 13 14 15 16 17 18 19]
Product of 2 Vectors:  [ 11  24  39  56  75  96 119 144 171]


25. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

In [27]:
# array.reshape(shape): This method is used to change the current shape of the array to the specified shape.
print('3x4 matrix with values 10 to 21: ', np.arange(10, 22).reshape((3, 4)))

3x4 matrix with values 10 to 21:  [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


26. Write a NumPy program to find the number of rows and columns in a given matrix.

In [28]:
# array.shape : This method returns the shape of an array which suggest the number of rows and cols
arr = np.arange(20).reshape((4,5))
print('Shape of the array: ', arr.shape)

Shape of the array:  (4, 5)


27. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal elements are 1, the rest are 0.

In [29]:
# np.identity(size) : This method returns an identity matrix of specified 'size'
# np.eye(shape) : This method returns a diagonal matrix with values 1 in diagonals of specified shape.
print('Identity Matrix: ', np.identity(3))

print('Identity Matrix: ', np.eye(4,3))

Identity Matrix:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Identity Matrix:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


28. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [30]:
# np.ones(shape) : This method creates a matrix with specified shape
arr = np.ones((10,10))

# array[row, col] is used here..!
# rows range from 1 to -2 and cols range from 1 to -2 are filtered out and assigned value = 0
arr[1:-1,1:-1] = 0

print('10x10 matrix with borders 1 and inside 0: ', arr)

10x10 matrix with borders 1 and inside 0:  [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


29. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [31]:
# np.diag(array) : This method returns a diagonal matrix with diagonal elements as the elements from array specified and remaining elements are 0.
print('Diagonal Matrix: ', np.diag([1,2,3,4,5]))

Diagonal Matrix:  [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


30. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.
    

In [32]:
# create an array of zeros
# np.zeros(shape) : This will create an array with specified Shape
arr = np.zeros((4,4))

# this filters odd rows, sets the value = 1 in all the cols with step = 2
arr[1::2, ::2] = 1

# this filters odd cols, sets the value = 1 in all the rows with step = 2
arr[::2, 1::2] = 1

print('Staggered Matrix: ', arr)

Staggered Matrix:  [[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


31. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.


In [33]:
# np.random.rand(shape) : This method returns an array of specified shape with random values between 0 and 1
arr = np.random.random((3, 3, 3))
print('Array: ', arr)

Array:  [[[0.61026108 0.072974   0.07603634]
  [0.2962262  0.86661282 0.60658154]
  [0.35033709 0.69666342 0.25055452]]

 [[0.63674373 0.89132889 0.47941299]
  [0.70211422 0.4299569  0.30661499]
  [0.29809732 0.12613752 0.28179186]]

 [[0.28290064 0.11096405 0.71882367]
  [0.14537186 0.59824869 0.76261307]
  [0.58955799 0.35247152 0.19515145]]]


32. Write a NumPy program to compute the sum of all elements, the sum of each column and the sum of each row in a given array.


In [34]:
# creating 20 random integers 
# np.random.randint(start, stop, size) : This method generates the specified size of random integers between the range start and stop
arr = np.random.randint(15, 75, 20).reshape(4,5)
print('Original Array: ', arr)

# np.sum(array) : this method is used to compute the sum of all elements.
print('Sum of Elements: ', np.sum(arr))

# np.sum(array, axis=0) : when axis = 0, this method compute the sum of elements in column wise
# np.sum(array, axis=1) : when axis = 1, this method compute the sum of elements in row wise
print('Sum of cols: ', np.sum(arr, axis=0))
print('Sum of rows: ', np.sum(arr, axis=1))

Original Array:  [[50 18 49 59 64]
 [24 58 41 65 68]
 [70 26 18 73 49]
 [51 43 17 18 24]]
Sum of Elements:  885
Sum of cols:  [195 145 125 215 205]
Sum of rows:  [240 256 236 153]


33. Write a NumPy program to compute the inner product of two given vectors.


In [35]:
# Create two random integer arrays of size 4
arr1 = np.random.randint(1, 20, 4)
arr2 = np.random.randint(12, 22, 4)

print('Array1: ', arr1)
print('Array2: ', arr2)

# np.dot(array1, array2) : Returns the dot product of two specified arrays.
print('Inner Product: ', np.dot(arr1, arr2))

Array1:  [10  8  9 19]
Array2:  [21 12 16 19]
Inner Product:  811


34. Write a NumPy program to add a vector to each row of a given matrix.


In [37]:
# create a vector
vector = np.array([1,2,3])
print('Vector: ', vector)

# create a matrix
matrix = np.random.randint(12, 22, 12).reshape(4,3)
print('Matrix: ', matrix)

# np.empty_like(array) : This method creates an empty array
for i in range(4):
    matrix[i,:] += vector

print('New Matrix: ', matrix)

Vector:  [1 2 3]
Matrix:  [[14 15 16]
 [20 17 12]
 [16 20 16]
 [13 16 21]]
New Matrix:  [[15 17 19]
 [21 19 15]
 [17 22 19]
 [14 18 24]]


35. Write a NumPy program to convert a given list into an array, then again convert it into a list. Check initial list and final list are equal or not.



In [38]:
# create a list
list1 = [1, 2, 44, 22, 12]
arr = np.array(list1)

# array.tolist() : This method is used convert a ndarray into list
list2 = arr.tolist()

print('List1 == List2: ', list1==list2)

List1 == List2:  True


36. Write a NumPy program to add elements to a matrix. If an element in the matrix is 0, we will not add the element below this element.


In [39]:
# create a matrix of shape (3, 3)
matrix = np.floor((np.random.rand(9)*10).reshape(3,3))
print('Original Matrix: ', matrix)

# np.sum(array) : This returns the total sum of all elements

for i in range(3):
    for j in range(3):
        if matrix[i,j] == 0 and i < 2:
            matrix[i+1,j] = 0
            
print('Sum: ', np.sum(matrix))


Original Matrix:  [[8. 2. 3.]
 [7. 0. 4.]
 [0. 5. 1.]]
Sum:  25.0


37. Write a NumPy program to find missing data in a given array.


In [40]:
# create an array
arr = np.array([2, np.nan, 22, 12, np.nan])

# np.isnan(array) : This checks if any data is not a number, if it finds returns True else false.
print('Missing Data: ', np.isnan(arr))

Missing Data:  [False  True False False  True]


38. Write a NumPy program to check whether two arrays are equal (element wise) or not.


In [41]:
# create 2 arrays of identical elements
arr1 = np.array([12,22,12,22])
arr2 = np.array([12,22,12,22])
print('Array1: ', arr1)
print('Array2: ', arr2)

# np.equal(array1, array2) : This method checks whether two arrays specified are equal element wise or not
# np.equal(array1, array2) is same as 'array1 == array2'
print(arr1 == arr2)

Array1:  [12 22 12 22]
Array2:  [12 22 12 22]
[ True  True  True  True]


39. Write a NumPy program to create a one-dimensional array of single, two and three-digit numbers.


In [42]:
# Vector : A vector is an one-dimensional array
# Single-digit numbers array
arr1 = np.arange(10)

# Two-digit numbers array
arr2 = np.random.randint(10, 100, 10)

# Three-digit numbers array
arr3 = np.random.randint(100, 1000, 10)

print('Single-digit Numbers: ', arr1)
print('Two-digit Numbers: ', arr2)
print('Three-digit Numbers: ', arr3)

Single-digit Numbers:  [0 1 2 3 4 5 6 7 8 9]
Two-digit Numbers:  [27 50 76 73 66 87 11 20 95 49]
Three-digit Numbers:  [315 691 950 970 554 690 316 397 173 673]


40. Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values. Select random numbers from a uniform distribution between 0 and 1. 


In [43]:
# np.random.uniform(start, stop, size) : This method returns a vector of random numbers of specified 'size' in the range of 'start' to 'stop'.
# This method uses Uniform distribution between 0 and 1
arr = np.random.uniform(0,1,40)
print('Array: ', arr)

Array:  [0.77290144 0.47035132 0.30523044 0.62340722 0.45661865 0.34172024
 0.40322505 0.31696693 0.12818247 0.08794418 0.75063521 0.75086829
 0.9321494  0.33347446 0.03247628 0.36821679 0.26977975 0.64064653
 0.50884462 0.02176668 0.46286518 0.6130549  0.89194476 0.96937347
 0.36920283 0.23652618 0.93558391 0.29907084 0.97035775 0.45431138
 0.45553317 0.50771772 0.60135231 0.4503333  0.68480679 0.34662174
 0.02673659 0.73733264 0.53154005 0.64510179]


41. Write a NumPy program to create a two-dimensional array with shape (8,5) of random numbers. Select random numbers from a normal distribution (200,7).


In [44]:
# np.random.normal(mean, std, size) : This method select the random numbers from the normal distribution with specified 'size'
# array.reshape(shape) : This method allows us to reshape an array to specified 'shape'
arr = np.random.normal(200, 7, 40).reshape(8, 5)
print('Array: ', arr)

Array:  [[208.83549457 201.82271798 209.55969326 188.78791042 208.93699004]
 [185.08441386 204.97529914 197.38344093 200.09980731 198.20100926]
 [198.26746055 207.84638881 203.78343287 208.31366861 192.20806192]
 [198.53410874 196.37073817 208.9071386  207.81609931 193.89380306]
 [197.9011078  207.24378232 191.76488649 195.40191318 201.21904953]
 [204.31504335 210.21378094 207.04727156 202.00790996 191.32134053]
 [196.30798206 207.48251235 193.72043446 204.04053295 203.40945045]
 [203.31289221 202.63307184 206.86601078 196.95748715 209.86625218]]


41. Write a NumPy program to generate a uniform, non-uniform random sample from a given 1-D array with and without replacement.



In [45]:
# np.random.choice(range, size, replace=True, p) : This method creates Uniform random sample of specified 'size' when p (i.e. probabilities which should sum to 1) is not specified.
# And creates Non-Uniform random sample if p is specified. The 'replace=True' is default for with replacement.

# Uniform random sample with replacement
arr1 = np.random.choice(10, 5, replace=True)

# Uniform random sample without replacement
arr2 = np.random.choice(10, 5, replace=False)

# Non-Uniform random sample with replacement
arr3 = np.random.choice(10, 5, replace=True, p=[0.1, 0.2, 0, 0.1, 0.1, 0.1, 0.2, 0.1, 0.1, 0])

# Non-Uniform random sample without replacement
arr4 = np.random.choice(10, 5, replace=False, p=[0.1, 0.2, 0, 0.1, 0.1, 0.1, 0.2, 0.1, 0.1, 0])

print('Uniform Random Sample With Replacement: ', arr1)
print('Uniform Random Sample Without Replacement: ', arr2)
print('Non-Uniform Random Sample With Replacement: ', arr3)
print('Non-Uniform Random Sample Without Replacement: ', arr4)

Uniform Random Sample With Replacement:  [6 9 3 8 8]
Uniform Random Sample Without Replacement:  [3 8 5 0 4]
Non-Uniform Random Sample With Replacement:  [7 1 0 6 4]
Non-Uniform Random Sample Without Replacement:  [0 6 5 1 7]


42. Write a NumPy program to create a 4x4 array with random values. Create an array from the said array swapping first and last rows.


In [46]:
# array.reshape(shape) : This method converts the array into specified shape.
# np.random.randint(start, stop, size) : This method create a random integer array with specified 'size' ranging from 'start' to 'stop'.
arr = np.random.randint(1206, 2209, 16).reshape(4, 4)
print('Original Array: ', arr)

# Swapping first and last row
arr[[0, -1],:] = arr[[-1, 0],:]

print('Swapped Array: ', arr)

Original Array:  [[1683 1881 2075 1683]
 [1408 1448 2063 2204]
 [1857 1219 1284 1797]
 [1498 1270 1266 1395]]
Swapped Array:  [[1498 1270 1266 1395]
 [1408 1448 2063 2204]
 [1857 1219 1284 1797]
 [1683 1881 2075 1683]]


43. Write a NumPy program to create a new array of given shape (5,6) and type, filled with zeros.


In [47]:
# np.zeros(size) : This returns an array of zeros of specified size
# given shape = (5, 6), therefor size = 5 * 6 i.e. 30.
arr = np.zeros(shape=(5, 6), dtype='int')
print('Array: ', arr)

Array:  [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


43. Write a NumPy program to sort a given array by row and column in ascending order.


In [48]:
# create a 2D array using np.random.randint(start, stop, size) method then reshape(shape) to it.
arr = np.random.randint(1206, 2209, 25).reshape(5, 5)
print('Original Array: ', arr)

# np.sort(array, axis=1) : This method sorts the array in ascending order.
# Row wise sorting is done if axis=1 (default).
print('Row-wise Sorted: ', np.sort(arr))

# Col wise sorting is done if axis=0.
print('Col-wise Sorted: ', np.sort(arr, axis=0))

Original Array:  [[1792 1706 2028 1815 2160]
 [2139 1971 1472 1619 1476]
 [1573 1289 1965 1755 1679]
 [1567 1672 1719 1292 2119]
 [1413 1397 1562 1702 1529]]
Row-wise Sorted:  [[1706 1792 1815 2028 2160]
 [1472 1476 1619 1971 2139]
 [1289 1573 1679 1755 1965]
 [1292 1567 1672 1719 2119]
 [1397 1413 1529 1562 1702]]
Col-wise Sorted:  [[1413 1289 1472 1292 1476]
 [1567 1397 1562 1619 1529]
 [1573 1672 1719 1702 1679]
 [1792 1706 1965 1755 2119]
 [2139 1971 2028 1815 2160]]


44. Write a NumPy program to extract all numbers from a given array less and greater than a specified number.


In [49]:
# create a vector using np.random.randint(start, stop, size)
arr = np.random.randint(1206, 2209, 12)
print('Original Array: ', arr)

# for less than use '<' operator inside the array as below which extract values less than 1800 from the array.
print('Nums < 1800: ', arr[arr < 1800])

# for greater than use '>' operator inside the array as below which extract values greater than 1800 from the array.
print('Nums > 1800: ', arr[arr > 1800])

Original Array:  [1744 1505 1291 1289 1792 1279 1915 1840 1946 1398 1967 1381]
Nums < 1800:  [1744 1505 1291 1289 1792 1279 1398 1381]
Nums > 1800:  [1915 1840 1946 1967]


45. Write a NumPy program to replace all numbers in a given array equal, less and greater than a given number.


In [50]:
# create a vector using np.random.randint(start, stop, size)
arr = np.random.randint(1206, 2209, 12)
print('Original Array: ', arr)

# np.where(condition, substitute, array) : This method replaces those elements with substitute in the specified array where the condition is true.
# replace 1500 if element equals to 1800
print('Replace 1500 for arr == 1800: ', np.where(arr == 1800, 1500, arr))

# replace1500 if element less than 1800
print('Replace 1500 for arr < 1800: ', np.where(arr < 1800, 1500, arr))

# replace 1500 if element greater than 1800
print('Replace 1500 for arr > 1800: ', np.where(arr > 1800, 1500, arr))

Original Array:  [1649 2039 1383 1290 1934 1927 1650 1321 1718 1308 1675 1998]
Replace 1500 for arr == 1800:  [1649 2039 1383 1290 1934 1927 1650 1321 1718 1308 1675 1998]
Replace 1500 for arr < 1800:  [1500 2039 1500 1500 1934 1927 1500 1500 1500 1500 1500 1998]
Replace 1500 for arr > 1800:  [1649 1500 1383 1290 1500 1500 1650 1321 1718 1308 1675 1500]


46. Write a NumPy program to create an array of equal shape and data type for a given array.


In [51]:
# create an array with np.arange(start, stop, dtype) then reshape(shape) it.
arr = np.arange(11, 23, dtype='int').reshape(3, 4)
print('Original Array: ', arr)

# np.zeros_like(array) : This method creates an array with same shape and dtype
# np.ones_like(array) : This method creates an array with same shape and dtype
# np.empty_like(array) : This method creates an array with same shape and dtype
print('Equal Shape and dtype Array: ', np.zeros_like(arr))

Original Array:  [[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
Equal Shape and dtype Array:  [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


47. Write a NumPy program to create a three-dimensional array with the shape (3,5,4) and set it to a variable.


In [52]:
# Given Shape = (3, 5, 4), therefor size will be 3 * 5 * 4 equals to 60
# create an array np.random.randint(start, stop, size).reshape(shape)

arr = np.random.randint(1206, 2209, 60).reshape(3, 5, 4)
print('3D Array: ', arr)

3D Array:  [[[1478 1789 1517 2142]
  [1616 1827 2051 1869]
  [1813 1565 1489 1453]
  [1735 1980 2178 1823]
  [1789 1572 2062 1460]]

 [[1453 1271 1817 2155]
  [2203 2026 1808 2199]
  [1332 1524 2055 1960]
  [2014 2063 2072 2070]
  [1360 1399 2144 1979]]

 [[2045 1650 1540 2089]
  [1960 1450 2142 1475]
  [1616 2117 2098 1853]
  [2070 1298 1317 1321]
  [1576 1839 1681 1558]]]


48. Write a NumPy program to create a 4x4 array. Create an array from said array by swapping first and last, second and third columns.


In [53]:
# create an array with np.random.randint(start, stop, size).reshape(shape)
# size = 4x4, therefor total elements equals to 16
arr = np.random.randint(1206, 2209, 16).reshape(4, 4)
print('Original Array: ', arr)

# swapping first and last cols
arr[:,[0, -1]] = arr[:,[-1, 0]]

# swapping second and third cols
arr[:,[1,2]] = arr[:,[2,1]]

print('Swapped Array: ', arr)

Original Array:  [[1529 1847 1417 2130]
 [1602 1429 1317 1616]
 [1384 1841 2053 1706]
 [2206 1222 1953 1802]]
Swapped Array:  [[2130 1417 1847 1529]
 [1616 1317 1429 1602]
 [1706 2053 1841 1384]
 [1802 1953 1222 2206]]


49. Write a NumPy program to swap rows and columns of a given array in reverse order.


In [54]:
# create an array with np.random.randint(start, stop, size).reshape(shape)
arr = np.random.randint(1206, 2209, 16).reshape(4, 4)
print('Original Array: ', arr)

# Swap Rows and Cols in reverse order using arr[::-1, ::-1]
print('Swapped Array: ', arr[::-1, ::-1])

Original Array:  [[1911 1937 1564 1863]
 [1573 1420 2101 2004]
 [1817 1767 1958 1349]
 [1877 1279 1264 2186]]
Swapped Array:  [[2186 1264 1279 1877]
 [1349 1958 1767 1817]
 [2004 2101 1420 1573]
 [1863 1564 1937 1911]]


50. Write a NumPy program to multiply two given arrays of the same size element-by-element.


In [55]:
# create two arrays using np.random.randint(start, stop, size).reshape(shape)
arr1 = np.random.randint(1206, 2209, 12).reshape(3,4)
print('Array1: ', arr1)

arr2 = np.random.randint(1206, 2209, 12).reshape(3,4)
print('Array2: ', arr2)

# use '*' (asterisk) for multiplying two arrays element-by-element
# np.multiply(array1, array2) : This method returns an array which is the product of two arrays element-wise
print('Product of Array1 and Array2: ', np.multiply(arr1, arr2))

Array1:  [[1340 1468 1765 2020]
 [1750 1993 2098 1343]
 [1997 1548 1868 1485]]
Array2:  [[1850 2034 1526 1967]
 [1297 1268 1281 2178]
 [1834 1430 1358 1890]]
Product of Array1 and Array2:  [[2479000 2985912 2693390 3973340]
 [2269750 2527124 2687538 2925054]
 [3662498 2213640 2536744 2806650]]
