In [1]:
# import the library numpy as np
import numpy as np

1. Write a NumPy program to generate five random numbers from the normal distribution.
1]

In [2]:
# np.random.normal(mean, std, size) : This method generates an array of specified size with random numbers whose mean and standard deviation is specified.
arr = np.random.normal(size=5)
print('Array: ', arr)

Array:  [-0.11309482 -1.14272738  0.09960119  0.15524989  0.71626443]


2. Write a NumPy program to generate six random integers between 10 and 30.

In [3]:
# np.random.randint(low, high, size) : This method generates random integers of specified size in range from low to high.
arr = np.random.randint(10, 30, 6)
print('Array: ', arr)

Array:  [20 27 21 16 20 29]


3. Write a NumPy program to create a 3x3x3 array with random values.

In [5]:
# np.random.random(shape) : This method generates random numbers between 0 and 1 of specified shape.
arr = np.random.random((3, 3, 3))
print('array: ', arr)

array:  [[[0.99755545 0.93970487 0.19040939]
  [0.40749014 0.32657371 0.95060331]
  [0.31316698 0.03866954 0.53320183]]

 [[0.1066338  0.94023233 0.67305623]
  [0.15016226 0.13663274 0.26924472]
  [0.09781205 0.1934168  0.85490508]]

 [[0.81616177 0.81868977 0.53486552]
  [0.20209309 0.0242171  0.25733673]
  [0.86727835 0.55591659 0.78565188]]]


4. Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

In [7]:
# np.random.random(shape) : This method generates random numbers between 0 and 1 of specified shape.
arr = np.random.random((5, 5))
print('array: ', arr)

# np.min(array) : This method gives the minimum value from the array.
# np.max(array) : This method gives the maximum value from the array.
print('MInimum: ', np.min(arr))
print('Maximum: ', np.max(arr))

array:  [[0.29935097 0.25358371 0.4440679  0.77949076 0.43297994]
 [0.73930476 0.74825361 0.17867052 0.9958229  0.54735623]
 [0.81284095 0.10228873 0.26759462 0.41715389 0.8645376 ]
 [0.6470091  0.15846267 0.62450256 0.63227072 0.77063894]
 [0.48194715 0.70402312 0.58117999 0.396211   0.98668964]]
MInimum:  0.10228873439955921
Maximum:  0.9958228990944301


5. Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.

In [9]:
# np.random.random(shape) : This method generates random numbers between 0 and 1 of specified shape.
arr = np.random.random((10, 4))
print('array: ', arr)

# Advanced Indexing is used to take out the first five rows of the array.
first_five_rows = arr[:5, :]
print('First five rows: ', first_five_rows)

array:  [[0.80463139 0.48584526 0.1013007  0.82389441]
 [0.10272199 0.4763658  0.00115383 0.14615665]
 [0.54975831 0.69935722 0.73788116 0.87428206]
 [0.26045699 0.1490203  0.19620473 0.61391868]
 [0.60955843 0.76883388 0.06197198 0.61193112]
 [0.75608571 0.87201351 0.67095929 0.63405802]
 [0.51888815 0.10989711 0.02172754 0.01043581]
 [0.15919468 0.10084636 0.71871993 0.78927824]
 [0.63862385 0.11456721 0.83786835 0.43265136]
 [0.47611156 0.53881078 0.17893774 0.72505958]]
First five rows:  [[0.80463139 0.48584526 0.1013007  0.82389441]
 [0.10272199 0.4763658  0.00115383 0.14615665]
 [0.54975831 0.69935722 0.73788116 0.87428206]
 [0.26045699 0.1490203  0.19620473 0.61391868]
 [0.60955843 0.76883388 0.06197198 0.61193112]]


6. Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).

In [12]:
# np.arange(start, stop, step) : this method creates an array in range from start to stop.
arr = np.arange(11)
print('Original Array: ', arr)

# np.random.shuffle(array) : This method shuffles the specified array randomly.
np.random.shuffle(arr)
print('Shuffled Array: ', arr)

Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10]
Shuffled Array:  [ 1  7  0  9  3  2 10  6  4  8  5]


7. Write a NumPy program to normalize a 3x3 random matrix.

In [15]:
# np.random.random(shape) : This method generates random numbers between 0 and 1 of specified shape.
arr = np.random.random((3, 3))
print('array: ', arr)

# min-max normalisation
# np.min(array) : This method gives the minimum value from the array.
# np.max(array) : This method gives the maximum value from the array.
mini, maxi = np.min(arr), np.max(arr)

arr = arr - mini/ mini + maxi
print('\nNormalised Array: ', arr)

array:  [[0.2825456  0.97485899 0.86332341]
 [0.32924418 0.07977352 0.48501952]
 [0.29561566 0.71577581 0.37008231]]

Normalised Array:  [[0.25740459 0.94971797 0.83818239]
 [0.30410317 0.05463251 0.45987851]
 [0.27047465 0.6906348  0.34494129]]


8. Write a NumPy program to create a random vector of size 10 and sort it.

In [33]:
vector = np.random.random(10)
print('Vector: ', vector)

# np.sort(array) : This method sorts the array that we pass to it.
print('\nSorted Vector: ', np.sort(vector))

Vector:  [0.28363607 0.20061206 0.42616823 0.37053867 0.70841533 0.30485953
 0.43538696 0.46096871 0.83703786 0.21920499]

Sorted Vector:  [0.20061206 0.21920499 0.28363607 0.30485953 0.37053867 0.42616823
 0.43538696 0.46096871 0.70841533 0.83703786]


9. Write a NumPy program to check two random arrays are equal or not.


In [36]:
# np.allclose(array1, array2) : this method checks element wise in both the array and returns true if both are equal.
arr1 = np.random.random(4)
print('Array1: ', arr1)
arr2 = np.random.random(4)
print('\nArray2: ', arr2)

print('\nIs_Array_Equal: ', np.allclose(arr1, arr2)) 

Array1:  [0.79546469 0.14647602 0.66671961 0.34466121]

Array2:  [0.63077308 0.77390731 0.85245247 0.68117924]

Is_Array_Equal:  False


10. Write a NumPy program to create random vector of size 15 and replace the maximum value by -1.


In [46]:
arr = np.random.random(15)
print('Vector: ', arr)

# np.argmax(array) : Returns the index of the maximum value in array.
# Using Advanced Indexing for Assigning -1 to maximum.

arr[np.argmax(arr)] = -1
print('\nMax Replaced Vector: ', arr)

Vector:  [0.57776664 0.55554136 0.58762784 0.04922165 0.6704031  0.05819908
 0.90903456 0.79814981 0.48656797 0.45832321 0.08356526 0.22904361
 0.75307472 0.24649467 0.38225729]

Max Replaced Vector:  [ 0.57776664  0.55554136  0.58762784  0.04922165  0.6704031   0.05819908
 -1.          0.79814981  0.48656797  0.45832321  0.08356526  0.22904361
  0.75307472  0.24649467  0.38225729]


13. Write a NumPy program to find the most frequent value in an array.

In [11]:
# create a random integer array of size 20.
arr = np.random.randint(22, size=20)
print('Original Array: ', arr)

# np.bincount(array): This function counts the number of occurrences of each non-negative integer in the array. It returns an array where the element 
#                at index i represents the count of the integer i in the input array.

# .bincount(array).argmax() : This function finds the index of the maximum element in the output array
print('Most Frequent Value In array: ', np.bincount(arr).argmax())

Original Array:  [ 6 10  3  3  7 12 16  2  2  8  5 15  2 17  7  9 12  1 13  8]
[0 1 3 2 0 1 1 2 2 1 1 0 2 1 0 1 1 1]
Most Frequent Value In array:  2


14. Write a NumPy program to create a three-dimension array with shape (300,400,5) and set to a variable. Fill the array elements with values using unsigned integer (0 to 255).


In [15]:
# np.random.randint(low, high, size) = Creates an array of specified size in the given range low to high.
# size = product of elements in shape.
arr = np.random.randint(0, 255, size=(300,400,5))
print('Original Array: ', arr)

Original Array:  [[[227  46 219 153  53]
  [ 83 174 204  26 156]
  [ 21 122 165 219  64]
  ...
  [170 230 176 127 130]
  [220 187  45 179 245]
  [ 58  47  86  11 229]]

 [[ 93 146 149 147 184]
  [  0 139  19 254 115]
  [223 142 135 142  71]
  ...
  [110 152  84 132 172]
  [  1 225 106 139  12]
  [ 88 113  95 102 102]]

 [[197 241 133 175 153]
  [224   4 149 164  62]
  [246 125  96 178 174]
  ...
  [159  81  36  49  21]
  [250 227 131 205 132]
  [165  97 117  93 234]]

 ...

 [[ 80 243 112  89  55]
  [221 205  11 152 238]
  [ 11 149 207 148  50]
  ...
  [185  43  99 177  92]
  [244  22   9 190  13]
  [226 203 124 115  18]]

 [[160  79  44  68 155]
  [ 27 159  26 173 239]
  [207 252  71   8 162]
  ...
  [200  17 160  51 129]
  [ 13 220   9 204 134]
  [ 43 203 225 147 159]]

 [[111 177  86  25  68]
  [156 196  66 141 156]
  [242  49 220 170 253]
  ...
  [224 146 222 110  74]
  [  8 108 221 155 211]
  [150  55   9 159 110]]]
