In [18]:
# import the numpy with alias np
import numpy as np

1. Write a NumPy program to add, subtract, multiply, divide, modulus arguments element-wise.


In [28]:
arr = np.arange(10, 26).reshape(4, 4)
print('Original Array: ', arr)

# addition ( + )
print('Add 5 to the each element of the array: ', arr + 5)

# subtraction ( - )
print('Subtract 5 from each element of the array: ', arr -5)

# multiplication ( * )
print('Multiply 5 to each element of the array: ', arr * 5)

# division ( / )
print('Divide each element of the array by 5: ', arr / 5)

# modulus( % )
print('Modulus of each element by 5: ', arr % 5)

Original Array:  [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
Add 5 to the each element of the array:  [[15 16 17 18]
 [19 20 21 22]
 [23 24 25 26]
 [27 28 29 30]]
Subtract 5 from each element of the array:  [[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
Multiply 5 to each element of the array:  [[ 50  55  60  65]
 [ 70  75  80  85]
 [ 90  95 100 105]
 [110 115 120 125]]
Divide each element of the array by 5:  [[2.  2.2 2.4 2.6]
 [2.8 3.  3.2 3.4]
 [3.6 3.8 4.  4.2]
 [4.4 4.6 4.8 5. ]]
Modulus of each element by 5:  [[0 1 2 3]
 [4 0 1 2]
 [3 4 0 1]
 [2 3 4 0]]


2. Write a NumPy program to get true division of the element-wise array inputs.


In [25]:
# np.true_divide(array, divident) : This function perform true division of array with the divident
arr = np.arange(10)
print('Original Array: ', arr)

print('True Division: ', np.true_divide(arr, 3))

Original Array:  [0 1 2 3 4 5 6 7 8 9]
True Division:  [0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]


3. Write a NumPy program to get the powers of an array values element-wise.

In [27]:
arr = np.arange(10)
print('Original Array: ', arr)

# np.power(array, power) : this method raises the power of each element of the array and returns it.
print('Powers of the array Values: ', np.power(arr, 3))

Original Array:  [0 1 2 3 4 5 6 7 8 9]
Powers of the array Values:  [  0   1   8  27  64 125 216 343 512 729]


4. Write a NumPy program to calculate the absolute value element-wise.



In [30]:
arr = np.arange(-10, 10)
print('Original Array: ', arr)

# np.absolute(array) : This method generates absolute values of the array.
print('Absolute of array: ', np.absolute(arr))

Original Array:  [-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9]
Absolute of array:  [10  9  8  7  6  5  4  3  2  1  0  1  2  3  4  5  6  7  8  9]


5. Write a NumPy program to round array elements to the given number of decimals.


In [34]:
arr = np.random.random(10)
print('Original array: ', arr)

# np.round(array, rounding_no): This function rounds each element of the array to that digit after decimal specified in rounding_no.
print('Array rounded to 2 digits: ', np.round(arr, 2))

Original array:  [0.38109309 0.63961808 0.63655941 0.02747325 0.42059844 0.14247801
 0.74266299 0.55201185 0.63987314 0.52890663]
Array rounded to 2:  [0.38 0.64 0.64 0.03 0.42 0.14 0.74 0.55 0.64 0.53]


6. Write a NumPy program to round elements of the array to the nearest integer.


In [35]:
arr = np.random.random(10)
print('Original array: ', arr)

# np.rint(array) : This method round elements of the array to the nearest integer.
print('Nearest Integers: ', np.rint(arr))

Original array:  [0.31589696 0.42540307 0.77497105 0.77629354 0.63306794 0.31934245
 0.88363093 0.6996887  0.17800524 0.65260518]
Nearest Integers:  [0. 0. 1. 1. 1. 0. 1. 1. 0. 1.]


7. Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array.


In [37]:
arr = np.random.random(10)
print('Original array: ', arr)

# np.floor(array) : This function returns the floor value of each element of an array.
print('floor values: ', np.floor(arr))

# np.ceil(array) : This function returns the ceil value of each element of an array.
print('ceil values: ', np.ceil(arr))

# np.trunc(array) : this function returns the truncated values of the elements of an array.
print('truncated values: ', np.trunc(arr))

Original array:  [0.83299345 0.67244822 0.45988169 0.5668836  0.94129598 0.85093375
 0.04316281 0.65130943 0.26506264 0.83850538]
floor values:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
ceil values:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
truncated values:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


8. Write a NumPy program to multiply a 5x3 matrix by a 3x2 matrix and create a real matrix product.


In [40]:
matrix1 = np.random.randint(12, 22, size=(5, 3))
matrix2 = np.random.randint(12, 22, size=(3, 2))
print('Matrix1: ', matrix1)
print('Matrix2: ', matrix2)

# np.dot(matrix1, matrix2) : This method returns a real matrix product.
print('Real matrix product: ', np.dot(matrix1, matrix2))

Matrix1:  [[20 19 15]
 [16 21 12]
 [20 16 15]
 [19 19 19]
 [18 18 20]]
Matrix2:  [[14 16]
 [13 12]
 [12 13]]
Real matrix product:  [[707 743]
 [641 664]
 [668 707]
 [741 779]
 [726 764]]


9. Write a NumPy program to multiply a matrix by another matrix of complex numbers and create a new matrix of complex numbers.

In [43]:
mat1 = np.array([1+2j, 3+4j])
mat2 = np.array([5+6j, 7+8j])

# np.vdot(matrix1, matrix2) : This method returns a vector matrix product.
print('complex matrix product: ', np.vdot(mat1, mat2))

complex matrix product:  (-18+68j)


10. Write a NumPy program to generate inner, outer, and cross products of matrices.


In [44]:
arr1 = np.random.randint(12, 22, size=(2, 2))
print('Matrix1: ', arr1)

arr2 = np.random.randint(12, 22, size=(2, 2))
print('\nMatrix2: ', arr2)

# np.inner(matrix1, matrix2): this function returns the inner product of the two matrices specified.
print('\nInner product: ', np.inner(arr1, arr2))

# np.outer(matrix1, matrix2) : this function returns the outer product of the two matrices specified.
print('\nOuter product: ', np.outer(arr1, arr2))

# np.cross(matrix1, matrix2) : this function returns the cross product of the two matrices specified.
print('\nCross product: ', np.cross(arr1, arr2))

Matrix1:  [[21 16]
 [15 12]]

Matrix2:  [[14 15]
 [21 12]]

Inner product:  [[534 633]
 [390 459]]

Outer product:  [[294 315 441 252]
 [224 240 336 192]
 [210 225 315 180]
 [168 180 252 144]]

Cross product:  [ 91 -72]


11. Write a NumPy program to find the roots of the following polynomials.


In [50]:
# np.roots(array) : This method returns the roots of a polynomial.
# let we have polynomial: 7x^3 + 3x^2 - 12x + 15 = 0
# np.roots([7, 3, -12, 15]) will give the roots of this polynomial. The array that we pass contains the coefficients of the polynomial

print('Roots of the polynomial 7x^3 + 3x^2 - 12x + 15 = 0: ', np.roots([7, 3, -12, 15]))

Roots of the polynomial 7x^3 + 3x^2 - 12x + 15 = 0:  [-1.91167636+0.j          0.74155247+0.75566584j  0.74155247-0.75566584j]


12. Write a NumPy program to compute the following polynomial values.


In [51]:
# np.polyval(array, x_value) : This function computes f(x_value) and returns. The array contains coefficients of the polynomial.
print('polynomial value when x = 2: ', np.polyval([1, -2, 6], 2))

polynomial value when x = 2:  6


12. Write a NumPy program to add one polynomial to another, subtract one polynomial from another, multiply one polynomial by another and divide one polynomial by another.


In [56]:
# np.polyadd(array1, array2) : this function add the two polymials. Here arrays contain the coefficients.
print('Polynomial Addition: ', np.polyadd([1, 2, 3], [4, 5, 6]))

# np.polysub(array1, array2) : this function subtract polynomial2 from polynomial1. Here arrays contain the coefficients.
print('\nPolynomial Subtraction: ', np.polysub([1, 2, 3], [4, 5, 6]))

# np.polymul(array1, array2) : this function multiplies polynomial1 with polynomial2. Here arrays contain the coefficients.
print('\nPolynomial Multiplication: ', np.polymul([1, 2, 3], [4, 5, 6]))

# np.polydiv(array1, array2) : this function divides polynomial1 by polynomial2. Here arrays contain the coefficients.
print('\nPolynomial division: ', np.polydiv([1, 2, 3], [4, 5, 6]))

Polynomial Addition:  [5 7 9]

Polynomial Subtraction:  [-3 -3 -3]

Polynomial Multiplication:  [ 4 13 28 27 18]

Polynomial division:  (array([0.25]), array([0.75, 1.5 ]))


13. Write a NumPy program to calculate mean across dimension, in a 2D numpy array.


In [60]:
arr = np.random.randint(12, size=(3, 3))
print('Original Array: ', arr)

# np.mean(array, axis) : This function returns the mean of array as per the axis mentioned.
# if axis = 0, goes for cols
print('\nMean in cols: ', np.mean(arr, axis=0))

# if axis = 1, goes for rows
print('\nMean in rows: ', np.mean(arr, axis=1))

Original Array:  [[9 7 6]
 [4 1 3]
 [0 5 0]]

Mean in cols:  [4.33333333 4.33333333 3.        ]

Mean in rows:  [7.33333333 2.66666667 1.66666667]


14. Write a NumPy program to create a random array with 1000 elements and compute the average, variance, standard deviation of the array elements.

In [63]:
arr = np.random.random(1000)
# print('Original Array: ', arr)

# average is obtained using np.mean(array, axis).
print('\nAverage: ', np.mean(arr))

# np.var(array, axis) : This method returns the variance of the array.
print('\nVariance: ', np.var(arr))

# np.std(array, axis) : This method returns the standard deviation of the array.l
print('\nStandard Deviation: ', np.std(arr))


Average:  0.4917013251008242

Variance:  0.08754286892558438

Standard Deviation:  0.295876441991559


15. Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degrees.

In [70]:
# create an array for angles given in degrees.
arr = np.array([15, 30, 45, 60, 90, 120, 150, 180])
print('Array of degrees: ', arr)

# np.pi = This is the pi value. to convert 
# np.pi/180 converts the degree value to radian value.

# np.sin(array) : This function gives the sin values for each element in the array.
print('\nSin values: ', np.sin(arr * np.pi/180) )

# np.cos(array) : This function gives the cos values for each element in the array.
print('\nCos values: ', np.cos(arr * np.pi/180))

# np.tan(array) : This function gives the tan values for each element in the array.
print('\nTan values: ', np.tan(arr * np.pi/180))

Array of degrees:  [ 15  30  45  60  90 120 150 180]

Sin values:  [2.58819045e-01 5.00000000e-01 7.07106781e-01 8.66025404e-01
 1.00000000e+00 8.66025404e-01 5.00000000e-01 1.22464680e-16]

Cos values:  [ 9.65925826e-01  8.66025404e-01  7.07106781e-01  5.00000000e-01
  6.12323400e-17 -5.00000000e-01 -8.66025404e-01 -1.00000000e+00]

Tan values:  [ 2.67949192e-01  5.77350269e-01  1.00000000e+00  1.73205081e+00
  1.63312394e+16 -1.73205081e+00 -5.77350269e-01 -1.22464680e-16]


16. Write a NumPy program to calculate inverse sine, inverse cosine, and inverse tangent for all elements in a given array.


In [72]:
arr = np.random.rand(10)
print('Original Array: ', arr)

# np.arcsin(array) : This method returns the inverse sine values of elements.
print('\nInverse Sin: ', np.arcsin(arr) * 180/np.pi)

# np.arccos(array) : This method returns the inverse cosine values of elements.
print('\nInverse Cos: ', np.arccos(arr) * 180/np.pi)

# np.arctan(array) : This method returns the inverse tan values of elements.
print('\nInverse Tan: ', np.arctan(arr) * 180/np.pi)

Original Array:  [0.66462791 0.7200709  0.48285037 0.24181494 0.30489084 0.91552921
 0.60517749 0.1695493  0.32951266 0.69532918]

Inverse Sin:  [41.65378585 46.06033407 28.8717304  13.99368425 17.75159649 66.28099425
 37.24161525  9.76161561 19.23919876 44.0534545 ]

Inverse Cos:  [48.34621415 43.93966593 61.1282696  76.00631575 72.24840351 23.71900575
 52.75838475 80.23838439 70.76080124 45.9465455 ]

Inverse Tan:  [33.60912139 35.75656239 25.77359085 13.59401747 16.95598341 42.47501313
 31.1813823   9.62294572 18.23770604 34.81201626]


17. Write a NumPy program to calculate cumulative sum of the elements along a given axis, sum over rows for each of the 3 columns and sum over columns for each of the 2 rows of a given 3x3 array.

In [ ]:
arr = np.random.randint(12, 22, size=(3, 3))
print('Original Array: ', arr)

# np.cumsum(array, axis) : this function gives the cumulative sum of the elements along a given axis.
# if axis = 0, cumsum of cols is computed
print('\nCumulative Sum along cols: ', np.cumsum(arr, axis=0))

# if axis = 1, cumsum of rows is computed
print('\nCumulative Sum along rows: ', np.cumsum(arr, axis=1))

18. Write a NumPy program to calculate cumulative product of the elements along a given axis, sum over rows for each of the 3 columns and product over columns for each of the 2 rows of a given 3x3 array.

In [76]:
arr = np.random.randint(12, 22, size=(3, 3))
print('Original Array: ', arr)

# np.cumprod(array, axis) : this function gives the cumulative product of the elements along a given axis.
# if axis = 0, cumprod of cols is computed
print('\nCumulative Product along cols: ', np.cumprod(arr, axis=0))

# if axis = 1, cumprod of rows is computed
print('\nCumulative Product along rows: ', np.cumprod(arr, axis=1))

Original Array:  [[18 14 12]
 [18 21 12]
 [18 19 13]]

Cumulative Product along cols:  [[  18   14   12]
 [ 324  294  144]
 [5832 5586 1872]]

Cumulative Product along rows:  [[  18  252 3024]
 [  18  378 4536]
 [  18  342 4446]]


19. Write a NumPy program to calculate the difference between neighboring elements, element-wise of a given array.

In [79]:
arr = np.random.randint(12, 22, 10)
print('Original Array: ', arr)

# np.diff(array) : this function returns the difference between neighboring elements, element-wise.
print('\nElement Wise Difference: ', np.diff(arr))

Original Array:  [20 15 21 13 12 12 21 20 13 18]

Element Wise Difference:  [-5  6 -8 -1  0  9 -1 -7  5]


20. Write a NumPy program to compute e^x, element-wise of a given array.


In [80]:
arr = np.random.randint(12, 22, 10)
print('Original Array: ', arr)

# np.exp(array) : This function computes e^x, element wise of a given array.
print('\n e^x : ', np.exp(arr))

Original Array:  [16 12 19 13 18 13 19 12 19 12]

 e^x :  [8.88611052e+06 1.62754791e+05 1.78482301e+08 4.42413392e+05
 6.56599691e+07 4.42413392e+05 1.78482301e+08 1.62754791e+05
 1.78482301e+08 1.62754791e+05]


21. Write a NumPy program to calculate 2p for all elements in a given array.

In [81]:
arr = np.random.randint(12, 22, 10)
print('Original Array: ', arr)

# np.exp2(array) : This function computes 2^p, element wise of a given array.
print('\n 2^p: ', np.exp2(arr))

Original Array:  [19 16 18 19 19 17 13 15 14 15]

 2^p:  [524288.  65536. 262144. 524288. 524288. 131072.   8192.  32768.  16384.
  32768.]


22. Write a NumPy program to compute natural, base 10, and base 2 logarithms for all elements in a given array.

In [82]:
arr = np.random.randint(12, 22, 10)
print('Original Array: ', arr)

# np.log(array) : finds out the natural logarithm
print('\nNatural Logarithm: ', np.log(arr))

# np.log10(array) : finds the logarithm of base 10
print('\nBase 10 logarithm: ', np.log10(arr))

# np.log2(array) : finds the logarithm of base 2
print('\nBase 2 logarithm: ', np.log2(arr))

Original Array:  [21 19 17 17 19 20 19 15 19 13]

Natural Logarithm:  [3.04452244 2.94443898 2.83321334 2.83321334 2.94443898 2.99573227
 2.94443898 2.7080502  2.94443898 2.56494936]

Base 10 logarithm:  [1.32221929 1.2787536  1.23044892 1.23044892 1.2787536  1.30103
 1.2787536  1.17609126 1.2787536  1.11394335]

Base 2 logarithm:  [4.39231742 4.24792751 4.08746284 4.08746284 4.24792751 4.32192809
 4.24792751 3.9068906  4.24792751 3.70043972]


23. Write a NumPy program to compute the reciprocal for all elements in a given array.
:

In [90]:
arr = np.random.randint(12, 22, 10)
print('Original Array: ', arr)

# np.reciprocal(array) : This function returns the reciprocal of each element of an array.
reciprocals = 1/arr

print('\nReciprocals: ', reciprocals)

Original Array:  [13 18 16 21 16 14 17 16 20 14]

Reciprocals:  [0.07692308 0.05555556 0.0625     0.04761905 0.0625     0.07142857
 0.05882353 0.0625     0.05       0.07142857]
