In [91]:
# import the library numpy with alias np
import numpy as np

1. Write a Python program to find the maximum and minimum value of a given flattened array.


In [92]:
arr = np.random.randint(12, 22, 5)
print('Original Array: ', arr)

# np.max(array) : This method returns the maximum value in the array.
print('\nMaximum: ', np.max(arr))

# np.min(array) : this method returns the minimum value in the array.
print('\nMinimum: ', np.min(arr))

Original Array:  [17 15 20 20 14]

Maximum:  20

Minimum:  14


2. Write a NumPy program to get the minimum and maximum value of a given array along the second axis.


In [94]:
arr = np.random.randint(12, 22, size=(3, 4))
print('Original Array: ', arr)

# np.max(array, axis) : This method returns the maximum value in the array along the given axis.
print('\nMaximum along 2nd axis: ', np.max(arr, axis=1))

# np.min(array, axis) : This method returns the minimum value in the array along the given axis.
print('\nMinimum along 2nd Axis: ', np.min(arr, axis=1))

Original Array:  [[15 15 21 16]
 [12 15 18 14]
 [18 21 13 14]]

Maximum along 2nd axis:  [21 18 21]

Minimum along 2nd Axis:  [15 12 13]


3. Write a NumPy program to compute the 80th percentile for all elements in a given array along the second axis.

In [95]:
arr = np.random.randint(12, 22, size=(3, 4))
print('Original Array: ', arr)

# np.percentile(array, percentile_value, axis) : This method computes the percentilel for all elements in a given array along the second axis.
print('\n80th percentiles: ', np.percentile(arr, 80, 1))

Original Array:  [[16 15 19 12]
 [21 14 12 18]
 [14 13 20 14]]

80th percentiles:  [17.2 19.2 16.4]


4. Write a NumPy program to compute the median of flattened given array.

In [97]:
arr = np.random.randint(12, 22, 15)
print('Original Array: ', arr)

# np.median(array) : This method returns the median of the array given.
print('\nMedian: ', np.median(arr))

Original Array:  [18 15 14 20 15 14 19 16 12 18 16 16 13 14 14]

Median:  15.0


5. Write a NumPy program to compute the mean, standard deviation, and variance of a given array along the second axis.


In [101]:
arr = np.random.randint(12, 22, (4, 4))
print('Original Array: ', arr)

# np.mean(array) : Returns the mean of the array specified.
print('\nMean of the array: ', np.mean(arr))

# np.std(array) : Returns the standard deviation of the array specified.
print('\nStandard Deviation of the array: ', np.std(arr))

# np.var(array) : Returns the variance of the array specified.
print('\nVariance of the array: ', np.var(arr))

Original Array:  [[13 13 15 19]
 [20 12 15 16]
 [21 19 19 14]
 [18 16 15 17]]

Mean of the array:  16.375

Standard Deviation of the array:  2.6427968139832467

Variance of the array:  6.984375


6. Write a NumPy program to compute the covariance matrix of two given arrays.


In [102]:
arr1 = np.random.randint(12, 22, 5)
arr2 = np.random.randint(12, 22, 5)

print('Array1: ', arr1)
print('\nArray2: ', arr2)

# np.cov(array1, array2) : computes the covariance matrix of the two given arrays.
print('\nCovariance Matrix: ', np.cov(arr1, arr2))

Array1:  [16 21 20 13 13]

Array2:  [16 16 19 21 20]

Covariance Matrix:  [[14.3  -5.55]
 [-5.55  5.3 ]]


7. Write a NumPy program to compute cross-correlation of two given arrays.


In [103]:
arr1 = np.random.randint(12, 22, 5)
arr2 = np.random.randint(12, 22, 5)

print('Array1: ', arr1)
print('\nArray2: ', arr2)

# np.corr(array1, array2) : This function computes cross-correlation of two given arrays.
print('\nCross-Correlation: ', np.correlate(arr1, arr2))

Array1:  [18 17 14 19 16]

Array2:  [14 21 17 15 12]

Cross-Correlation:  [1324]


8. Write a NumPy program to compute pearson product-moment correlation coefficients of two given arrays.


In [105]:
arr1 = np.random.randint(12, 22, 5)
arr2 = np.random.randint(12, 22, 5)

print('Array1: ', arr1)
print('\nArray2: ', arr2)

# np.corrcoef(array1, array2) : computes correlation coefficients of two given arrays.
print('\nPearson product-moment correlation coefficients: ', np.corrcoef(arr1, arr2))

Array1:  [21 13 20 12 14]

Array2:  [18 17 19 17 13]

Pearson product-moment correlation coefficients:  [[1.         0.55034954]
 [0.55034954 1.        ]]
