In [1]:
# Import the library numpy with alias np
import numpy as np

1. Write a NumPy program to print the NumPy version on your system.


In [3]:
# np.__version__ : This gives us the version of numpy that we are using
print('Numpy Version: ', np.__version__)

Numpy Version:  1.26.4


2. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]

In [9]:
# create the list as given in question
original_list = [12.23, 12.32, 100, 36.32]
print('Original List: ', origina_list)

# np.array(iterable) : This method is used to create ndarray from the specified iterable.
arr = np.array(original_list)
print('Numpy Array: ', arr)

Original List:  [12.23, 12.32, 100, 36.32]
Numpy Array:  [ 12.23  12.32 100.    36.32]


3.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]

In [13]:
# np.arange(start, stop, step) : This method creates an ndarray within a given range from 'start' to 'stop' as specified with default 'step' = 1.
# array.reshape(shape) : This method reshape's an array to the specified shape.
arr = np.arange(2, 11).reshape(3, 3)

print(arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


4. Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [19]:
# np.zeros(shape) : This method creates an ndarray with elements as zero as per the specified shape.
arr = np.zeros(10)

# To assign sixth value to 11, we need to access the index = 6, because array indexing starts from 0.
arr[6] = 11

print(arr)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


5. Write a NumPy program to create an array with values ranging from 12 to 38.
Expected Output:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

In [20]:
# np.arange(start, stop, step) : This method creates an ndarray within a given range from 'start' to 'stop' as specified with default 'step' = 1.
arr = np.arange(12, 38)
print(arr)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


6. Write a NumPy program to reverse an array (the first element becomes the last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [21]:
# np.arange(start, stop, step) : This method creates an ndarray within a given range from 'start' to 'stop' as specified with default 'step' = 1.
arr = np.arange(12, 38)
print('Original Array: ', arr)

# to reverse an array, use advance indexing like arr[::-1]
print('Reverse array: ',arr[::-1])

Original Array:  [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:  [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


7. Write a NumPy program to convert an array to a floating type.
Sample output:
Original array
[1, 2, 3, 4]
Array converted to a float type:
[ 1. 2. 3. 4.]

In [24]:
# np.array(iterable) : This method creates an array out of the iterable specified.
# by using dtype='float', we can convert the array to a float type, which default
arr = np.array([1,2,3,4], dtype='float')

print(arr)

[1. 2. 3. 4.]


8. Write a NumPy program to create a 2D array with 1 on the border and 0 inside.
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]

In [34]:
# np.ones(shape) : This method creates an array of specified shape with elements as ones.
arr = np.ones((5,5))
print('Origina Array: ', arr)

# Using advanced indixing, assign value zero like arr[1:-1, 1: -1] = 0
arr[1:-1,1:-1] = 0

print('Expected Array: ', arr)

Origina Array:  [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Expected Array:  [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Write a NumPy program to add a border (filled with 0's) around an existing array.
Expected Output:
Original array:
[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 0. 0. 0. 0. 0.]
...........
[ 0. 0. 0. 0. 0.]]

In [37]:
# np.ones(shape) : This method creates an array of specified shape with elements as ones.
arr = np.ones((3,3))
print('Original Array: ', arr)

# np.pad(array, pad_width=1, mode='constant', constant_values=0): The np.pad function is used to pad the input array specified with a border of specified width and values. 
# In this case, pad_width=1 adds a border of width 1 around the array. The mode='constant' specifies that the padding should be done with constant values, and
# constant_values=0 indicates that the constant value for padding should be 0.
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print('Zero bordered Array: ', arr)

Original Array:  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Zero bordered Array:  [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


10. Write a NumPy program to create an 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
..........
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]

In [46]:
# np.ones(shape) : This method creates an array of specified shape with elements as ones.
arr = np.ones((8, 8))
# print('Original Array: ', arr)

# To generate Checkerboard pattern, use advanced Indxing like: arr[::2, 1::2] = 0 and arr[1::2, ::2] = 0
arr[::2, 1::2] = 0
arr[1::2, ::2] = 0

print('Checkerboard Pattern: ', arr)

Checkerboard Pattern:  [[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


11. Write a NumPy program to convert a list and tuple into arrays.
List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
[1 2 3]]

In [47]:
# Use np.array(iterable) to create an array of iterables specified like list or tuple.
list = [1, 2, 3, 4, 5, 6, 7, 8]
tuple = ((8, 4, 6), (1, 2, 3))

print('List to Array: ', np.array(list))
print('Tuple to Array: ', np.array(tuple))

List to Array:  [1 2 3 4 5 6 7 8]
Tuple to Array:  [[8 4 6]
 [1 2 3]]


12. Write a NumPy program to append values to the end of an array.
Expected Output:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [49]:
# create an array of 10, 20, and 30 using np.array(iterable) method.
arr1 = np.array([10, 20, 30])
print('Original Array: ', arr1)

# np.append(array, appending_element/s) : This method is used to append the elements from 'appending_element/s'  to the specified 'array'
arr2 = np.append(arr1, [40, 50, 60, 70, 80, 90])
print('Appended Array: ', arr2)

Original Array:  [10 20 30]
Appended Array:  [10 20 30 40 50 60 70 80 90]


13. Write a NumPy program to create an empty and full array.
Expected Output:
[ 6.93270651e-310 1.59262180e-316 6.93270559e-310 6.93270665e-310]
[ 6.93270667e-310 6.93270671e-310 6.93270668e-310 6.93270483e-310]
[ 6.93270668e-310 6.93270671e-310 6.93270370e-310 6.93270488e-310]]
[[6 6 6]
[6 6 6]
[6 6 6]]

In [3]:
# np.empty(shape) : This method creates an empty array of specified shape.
empty_array = np.empty((3, 4))
print(empty_array)

# np.full(shape, element) : This method creates an array of specified shape with only one element i.e. specified.
full_array = np.full((3, 3), 6)
print(full_array)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 8.90095411e-307]
 [2.31423707e-306 7.56599807e-307 8.90104239e-307 3.11525958e-307]
 [1.69118108e-306 9.34608432e-307 1.42410974e-306 1.69119330e-306]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


14. Write a NumPy program to convert Centigrade degrees into Fahrenheit degrees. Centigrade values are stored in a NumPy array.
Values in Centigrade degrees:
[-17.78 -11.11 7.34 1.11 37.73 0. ]
Values in Fahrenheit degrees[-27.66 -23.95 -13.7  -17.16   3.18 -17.78]. ]73 0. ]

In [12]:
# create Fahrenheit Array to convert it into Centigrade Array
centigrade_array = np.array([-17.78, -11.11, 7.34, 1.11, 37.73, 0. ])
print('Values in Centigrade degrees: ', centigrade_array)

# fahrenheit = (centigrade - 32) * 5/9
# centigrade = (9/5 * fehrenheit) + 32

# np.round(array, round_value) : This method rounds the elements of the array specified w.r.t round_value.
fahrenheit_array = np.round((centigrade_array - 32) * 5/9, 2)

print('Values in Fahrenheit degrees: ', fahrenheit_array)

Values in Centigrade degrees:  [-17.78 -11.11   7.34   1.11  37.73   0.  ]
Values in Fahrenheit degrees:  [-27.66 -23.95 -13.7  -17.16   3.18 -17.78]


15. Write a NumPy program to find the real and imaginary parts of an array of complex numbers.
Expected Output:
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]
Real part of the array:
[ 1. 0.70710678]
Imaginary part of the array:
[ 0. 0.70710678]

In [17]:
# create a complen number array
complex_array =  np.array([1.00000000+0.j, 0.70710678+0.70710678j])
print('Original Array: ', complex_array)

# array.real : This gives the real parts of the elements of a complex array
print('Real part of the array: ', complex_array.real)

# array.imag : This gives the imaginary parts of the elements of a complex array
print('Imaginary part of the array: ', complex_array.imag)

Original Array:  [1.        +0.j         0.70710678+0.70710678j]
Real part of the array:  [1.         0.70710678]
Imaginary part of the array:  [0.         0.70710678]


16. Write a NumPy program to find the number of elements in an array. It also finds the length of one array element in bytes and the total bytes consumed by the elements.
Expected Output:
Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24

In [21]:
# array.size : This gives us the size of the array
# lets create an array with np.arange(start, stop, step)
arr = np.arange(1,4)
print('Size of the array: ', arr.size)

# array.itemsize : This gives the size of an array element in bytes
print('Length of one array element in bytes: ', arr.itemsize)

# Total bytes consumed = array.itemsize * array.size
print('Total bytes consumed by the array: ', arr.itemsize * arr.size)

Size of the array:  3
Length of one array element in bytes:  4
Total bytes consumed by the array:  12


17. Write a NumPy program to test whether each element of a 1-D array is also present in a second array.
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [0, 40]
Compare each element of array1 and array2
[ True False False True False]

In [4]:
# create two arrays using np.array(iterable)
arr1 = np.array([0, 10, 20, 40, 60])
print('Array1: ', arr1)

arr2 = np.array([0, 40])
print('Array2: ', arr2)

# np.in1d(array1, array2) : This method complares each element of array1 with array2 and returns True if found else false.
print('Comparision: ', np.in1d(arr1, arr2))

Array1:  [ 0 10 20 40 60]
Array2:  [ 0 40]
Comparision:  [ True False False  True False]


18. Write a NumPy program to find common values between two arrays.
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [10, 30, 40]
Common values between two arrays:
[10 40]

In [6]:
# create two arrays using np.array(iterable)
arr1 = np.array([0, 10, 20, 40, 60])
print('Array1: ', arr1)

arr2 = np.array([10, 30, 40])
print('Array2: ', arr2)

# np.intersect1d(array1, array2) : This method returns element of both arrays specified which are common.
print('Common Values: ', np.intersect1d(arr1, arr2))

Array1:  [ 0 10 20 40 60]
Array2:  [10 30 40]
Common Values:  [10 40]


19. Write a NumPy program to get the unique elements of an array.
Expected Output:
Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
[2 3]]
Unique elements of the above array:
[1 2 3]

In [8]:
# creatte an array using np.array(iterable)
Original_Array = np.array([10, 10, 20, 20, 30, 30])
print('Original Array: ', Original_Array)

# np.unique(array) : this method gives us the unique values in the array specified
print('Unique Elements: ', np.unique(Original_Array))

original_array2 = np.array([[1, 1], [2, 3]])
print('Original Array2: ', original_array2)

print('Unique Elements: ', np.unique(original_array2))

Original Array:  [10 10 20 20 30 30]
Unique Elements:  [10 20 30]
Original Array2:  [[1 1]
 [2 3]]
Unique Elements:  [1 2 3]


20. Write a NumPy program to find the set difference between two arrays. The set difference will return sorted, distinct values in array1 that are not in array2.
Expected Output:
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70, 90]
Set difference between two arrays:
[ 0 20 60 80]

In [9]:
# create two arrays with np.array(iterable)
arr1 = np.array([0, 10, 20, 40, 60, 80])
print('Array1: ', arr1)

arr2 = np.array([10, 30, 40, 50, 70, 90])
print('Array2: ', arr2)

# np.setdiff1d(array1, array2) : This method returns the set difference between array1 and array2: i.e. array1 - array2
print('Set Difference: ', np.setdiff1d(arr1, arr2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10 30 40 50 70 90]
Set Difference:  [ 0 20 60 80]


21. Write a NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return sorted, distinct values in only one (not both) of the input arrays.
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]

In [10]:
# create two arrays with np.array(iterable)
arr1 = np.array([0, 10, 20, 40, 60, 80])
print('Array1: ', arr1)

arr2 = np.array([10, 30, 40, 50, 70])
print('Array2: ', arr2)

# np.setxor1d(array1, array2) : Returns the set exclusive-or between the specified arrays.
print('Unique values: ', np.setxor1d(arr1, arr2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10 30 40 50 70]
Unique values:  [ 0 20 30 50 60 70 80]


22. Write a NumPy program to find the union of two arrays. Union will return a unique, sorted array of values in each of the two input arrays.
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70]
Unique sorted array of values that are in either of the two input arrays:
[ 0 10 20 30 40 50 60 70 80]

In [11]:
# create two arrays with np.array(iterable)
arr1 = np.array([0, 10, 20, 40, 60, 80])
print('Array1: ', arr1)

arr2 = np.array([10, 30, 40, 50, 70])
print('Array2: ', arr2)

# np.union1d(array1, array2) : This method returns the union of two arrays specified.
print('Union Array: ', np.union1d(arr1, arr2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10 30 40 50 70]
Union Array:  [ 0 10 20 30 40 50 60 70 80]


23. Write a NumPy program to test whether all elements in an array evaluate to True.
Note: 0 evaluates to False in NumPy.

In [17]:
# create an array using np.array(iter)
arr = np.array([12, 0, 22, 11, 1, 21, 10, 2, 20])
print('Original Array: ', arr)

# np.all(array) : This method returns false if any element is 0 or nan. Else it will return True.
print('Evaluation: ', np.all(arr))

Original Array:  [12  0 22 11  1 21 10  2 20]
Evaluation:  False


24. Write a NumPy program to test whether any array element along a given axis evaluates to True.
Note: 0 evaluates to False in NumPy.

In [18]:
# create an array using np.array(iter)
arr = np.array([12, 0, 22, 11, 1, 21, 10, 2, 20])
print('Original Array: ', arr)

# np.any(array) : This method returns True if any element is non-zero element. Else False.
print('Evaluation: ', np.any(arr))

Original Array:  [12  0 22 11  1 21 10  2 20]
Evaluation:  True


25. Write a NumPy program to construct an array by repeating.

Sample array: [1, 2, 3, 4]
Expected Output:
Original array
[1, 2, 3, 4]
Repeating 2 times
[1 2 3 4 1 2 3 4]
Repeating 3 times
[1 2 3 4 1 2 3 4 1 2 3 4]

In [22]:
# create the given array
sample_array = np.array([1, 2, 3, 4])
print('Original Array: ', sample_array)

# np.tile(array, n) : This method returns an array repeated n times as specified.
print('Repeating 2 times: ', np.tile(sample_array, 2))

# Repeating 3 times..
print('Repeating 3 times: ', np.tile(sample_array, 3))

Original Array:  [1 2 3 4]
Repeating 2 times:  [1 2 3 4 1 2 3 4]
Repeating 3 times:  [1 2 3 4 1 2 3 4 1 2 3 4]


26.Write a NumPy program to repeat array elements.
Expected Output:
[3 3 3 3]
[1 1 2 2 3 3 4 4]

In [24]:
# np.repeat(array, n): This method repeats each element in the array n times as specified.
arr1 = np.array([3])
print(np.repeat(arr1, 4))

arr2 = np.array([1, 2, 3, 4])
print(np.repeat(arr2, 2))

[3 3 3 3]
[1 1 2 2 3 3 4 4]


27. Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array.
Original array: [1 2 3 4 5 6]
Maximum Values: 5
Minimum Values: 0

In [29]:
arr = np.array([1, 2, 3, 4, 5, 6])
print('Original Array: ', arr)

# np.argmax(array) : This method returns the index of maximum element in the array specified.
print('Maximum Values: ', np.argmax(arr))

# np.argmin(array) : This method returns the index of minimum element in the array specified.
print('Minimum Values: ', np.argmin(arr))

Original Array:  [1 2 3 4 5 6]
Maximum Values:  5
Minimum Values:  0


28. Write a NumPy program to compare two arrays using NumPy.
Array a: [1 2]
Array b: [4 
e True]5]

In [30]:
arr1 = np.array([1, 2])
arr2 = np.array([4, 5])

# '>' operation
print('arr1 > arr2: ', arr1 > arr2)

# '>=' operation
print('arr1 >= arr2: ', arr1 >= arr2)

# '<' operation
print('arr1 < arr2: ', arr1 < arr2)

# '<=' operation
print('arr1 <= arr2: ', arr1 <= arr2)

arr1 > arr2:  [False False]
arr1 >= arr2:  [False False]
arr1 < arr2:  [ True  True]
arr1 <= arr2:  [ True  True]


29. Write a NumPy program to sort along the first and last axes of an array. Expected Output:
Original array:
[[4 6]
[2 1]]
Sort along the first axis:
[[2 1]
[4 6]]
Sort along the last axis:
[[1 2]
[4 6]]


In [48]:
arr = np.array([[4, 6], [2, 1]])
print('Original Array: ', arr)

# np.sort(array, axis) : This method is used to sort the array w.r.t axis
sorted_array1 = np.sort(arr, axis=0)
print('Sort along the first axis: ', sorted_array1)

sorted_array2 = np.sort(sorted_array1, axis=1)
print('Sort along the last axis: ', sorted_array2)

Original Array:  [[4 6]
 [2 1]]
Sort along the first axis:  [[2 1]
 [4 6]]
Sort along the last axis:  [[1 2]
 [4 6]]


30. Write a NumPy program to sort pairs of a first name and a last name and return their indices (first by last name, then by first name).
first_names = (Betsey, Shelley, Lanell, Genesis, Margery)
last_names = (Battle, Brien, Plotner, Stahl, Woolum)
Expected Output:
[1 3 2 4 0]

In [51]:
first_names = ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')

# np.lexsort(array1, array2) : This method sorts the elements of the specified arrays in dictionary order. This returns the array of indices that sorts the above
indices = np.lexsort((first_names, last_names))
print(indices)

[1 3 2 4 0]


Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.
Original array:
[[ 0 10 20]
[20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [54]:
original_array = np.array([[0, 10, 20], [20, 30, 40]])
print('Original array: ', original_array)

# values bigger than 10 using advanced indexing..
print('Values bigger than 10: ', original_array[original_array > 10])

# np.nonzero(condition) : This method allows us to extract the indices of the elements which satisfies the condition.
print('Indices are: ', np.nonzero(original_array > 10))

Original array:  [[ 0 10 20]
 [20 30 40]]
Values bigger than 10:  [20 20 30 40]
Indices are:  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


31. Write a NumPy program to create a contiguous flattened array.
Original array:
[[10 20 30]
[20 40 50]]
New flattened array:
[10 20 30 20 40 50]

In [56]:
arr = np.array([[10, 20, 30], [20, 40, 50]])
print('Original Array: ', arr)

# np.ravel(array) : This method flattens an array given to it.
print('New Flattened Array: ', np.ravel(arr))

Original Array:  [[10 20 30]
 [20 40 50]]
New Flattened Array:  [10 20 30 20 40 50]


32. Write a NumPy program to create a new array of 3*5, filled with 2.

In [61]:
# np.full(shape, fill_value) : This method is used to create an array of specified 'shape' with one element specified as 'fill_value'.
print(np.full(shape=(3, 5), fill_value=2))

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


33. Write a NumPy program to create an array of 10's with the same shape and type as the given array.
Sample array: x = np.arange(4, dtype=np.int64)
Expected Output:
[10 10 10 10]

In [62]:
# np.full(shape, fill_value) : This method is used to create an array of specified 'shape' with one element specified as 'fill_value'.
arr = np.arange(4, dtype=np.int64)
print(np.full(arr.shape, fill_value=10))

[10 10 10 10]


34. Write a NumPy program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere.
Expected Output:
[[4 0 0 0]
[0 5 0 0]
[0 0 6 0]
[0 0 0 8]]

In [67]:
# np.diag(array) : This method is used to create a diagonal array with diagonal elements specified as array.
print(np.diag([4, 5, 6, 7]))

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 7]]


35. Write a NumPy program to create a 1-D array of 30 evenly spaced elements between 2.5 and 6.5, inclusive.
Expected Output:
[ 2.5 2.63793103 2.77586207 2.9137931 3.05172414 3.18965517
.................
5.81034483 5.94827586 6.0862069 6.22413793 6.36206897 6.5 ]

In [68]:
# np.linspace(start, stop, size) : this method creates an array of specified size, evenly spaced between the range from start to stop.
print(np.linspace(2.5, 6.5, 30))

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


36. Write a NumPy program to create a 1-D array of 20 elements spaced evenly on a log scale between 2. and 5., exclusive.
Expected Output:
[ 100. 141.25375446 199.5262315 281.83829313
......................
25118.8643151 35481.33892336 50118.72336273 70794.57843841]

In [71]:
# np.logspace(start, stop, size, endpoint) : This method generated log scale of specified size, from range start to stop, and if endpoint=True (default) which includes stop.
print(np.logspace(2, 5, 20, endpoint=False))

[  100.           141.25375446   199.5262315    281.83829313
   398.10717055   562.34132519   794.32823472  1122.0184543
  1584.89319246  2238.72113857  3162.27766017  4466.83592151
  6309.5734448   8912.50938134 12589.25411794 17782.79410039
 25118.8643151  35481.33892336 50118.72336273 70794.57843841]


37. Write a NumPy program to create an array like the one below.
Expected Output
[[ 0.  0.  0.]                                                         
 [ 1.  0.  0.]                                                         
 [ 1.  1.  0.]                                                         
 [ 1.  1.  1.]]:

In [74]:
# np.tri(rows, cols, diagonal_shift) : This method creates a triangular array of elements 1. diagonal_shift specifies the shift of diagonal elements.
print(np.tri(4, 3, -1))

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


38. Write a NumPy program to create an array like the one below.
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 0 9 10]
[ 0 0 13]]

In [77]:
# np.triu(array, diagonal_shift): This method creates an upper triangle with elements in array. 
print(np.triu(np.arange(2, 14).reshape(4, 3), -1))

[[ 2  3  4]
 [ 5  6  7]
 [ 0  9 10]
 [ 0  0 13]]


39. Write a NumPy program to collapse a 3-D array into a one-dimensional array.
Expected Output:
3-D array:
[[ 1. 0. 0.]
[ 0. 1. 0.]
[ 0. 0. 1.]]
One dimension array:
[ 1. 0. 0. 0. 1. 0. 0. 0. 1.]

In [ ]:
# np.ravel(array) : This method flattens the array specified to 1D array.
# np.eye(shape) : This method creates an identity array.
arr = np.eye(3)
print('Original Array: ', arr)

print('1D array: ', np.ravel(arr))

40. Write a NumPy program to find the 4th element of a specified array.
Expected Output:
[[ 2 4 6]
[ 6 8 10]]
Forth e1ement of the array:
6

In [82]:
arr = np.array([[2, 4, 6], [6, 8, 10]])
print('Original Array: ', arr)

# array.flat(index) : This method returns the element at specified index when the array is flattened.
print('Fourth Element: ', arr.flat[3])

Original Array:  [[ 2  4  6]
 [ 6  8 10]]
Fourth Element:  6


41. Write a NumPy program to change two array axes.
Sample array: [[1 2 3]]
Expected Output:
[[1]
[2]
[3]]

In [85]:
# np.swapaxes(array, axis1, axis2) : this method swaps the axis1 with axis2 in the specified array.
arr = np.array([[1, 2, 3]])
print('Sample array: ', arr)

# here axes1 = 0, which denotes rows and axes2 = 1, which denotes cols.
print('Swapped Axes: ', np.swapaxes(arr, 0, 1))

Sample array:  [[1 2 3]]
Swapped Axes:  [[1]
 [2]
 [3]]


42. Write a NumPy program to move array axes to alternate positions. Other axes remain in their original order.
Expected Output:
(3, 4, 2)
(4, 2, 3)

In [7]:
arr = np.zeros((2, 3, 4))
print('Original Axes: ', arr.shape)

# np.moveaxis(array, source_axis, destination_axis) : This method is used to move source axis to destination.
# here source axis = 0, which moves to the place of destination axis i.e. -1
moved_axes = np.moveaxis(arr, 0, -1).shape
print('Moved Axes1: ', moved_axes)

print('Moved Axes2: ', np.moveaxis(arr.reshape(moved_axes), 0, -1).shape)

Original Axes:  (2, 3, 4)
Moved Axes1:  (3, 4, 2)
Moved Axes2:  (4, 2, 3)


43. Write a NumPy program to move the specified axis backwards, until it lies in a given position.
Move the following 3rd array axes to first position.
(2,3,4,5)
Sample Expected Output:
(2, 5, 3, 4)

In [10]:
arr = np.zeros((2, 3, 4, 5))
print('Original Axes: ', arr.shape)

# np.moveaxis(array, source_axis, destination_axis) : This method is used to move source axis to destination.
# here source axis = 5 in index 3, which moves to the place of destination axis i.e. 3 in index 1
moved_axes = np.moveaxis(arr, 3, 1).shape
print('Moved Axes: ', moved_axes)

Original Axes:  (2, 3, 4, 5)
Moved Axes:  (2, 5, 3, 4)


44. Write a NumPy program to insert a new axis within a 2-D array.
2-D array of shape (3, 4).
Expected Output:
New shape will be will be (3, 1, 4).

In [14]:
arr = np.zeros((3, 4))
print('Original Shape: ', arr.shape)

# np.expand_dims(array, axis) : This method will add the new axis specified to the array specified.
print('New Shape: ', np.expand_dims(arr, axis=1).shape)

Original Shape:  (3, 4)
New Shape:  (3, 1, 4)


45. Write a NumPy program to remove single-dimensional entries from a specified shape.
Specified shape: (3, 1, 4)
Expected Output: (3, 4)

In [15]:
arr = np.zeros((3, 1, 4))
print('Original Shape: ', arr.shape)

# np.squeeze(array) : this method will remove the single dimenstion entries from the array.
print('New Shape: ', np.squeeze(arr).shape)

Original Shape:  (3, 1, 4)
New Shape:  (3, 4)


46. Write a NumPy program to concatenate two 2-dimensional arrays.
Expected Output:
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]
Expected Output:
[[ 0 1 3 0 2 4]
[ 5 7 9 6 8 10]]

In [21]:
arr1 = np.array([[0, 1, 3], [5, 7, 9]])
arr2 = np.array([[0, 2, 4], [6, 8, 10]])
print('Array1: ', arr1)
print('Array2: ', arr2)

# np.concatenate((array1, array2), axis) : This method will concatenate array2 with array1 in specified axis.
print('Concatenated Array: ', np.concatenate((arr1, arr2), axis=1))

Array1:  [[0 1 3]
 [5 7 9]]
Array2:  [[ 0  2  4]
 [ 6  8 10]]
Concatenated Array:  [[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


47. Write a NumPy program to convert 1-D arrays as columns into a 2-D array.
Sample array: (10,20,30), (40,50,60)
Expected Output:
[[10 40]
[20 50]
[30 60]]

In [26]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([40, 50, 60])
print('Array1: ', arr1)
print('Array2: ', arr2)

# np.column_stack(array1, array2) : This method will create a stack of arrays in vertical order.
print('Output Array: ', np.column_stack((arr1, arr2)))

Array1:  [10 20 30]
Array2:  [40 50 60]
Output Array:  [[10 40]
 [20 50]
 [30 60]]


48. Write a NumPy program to convert (in sequence depth wise (along the third axis)) two 1-D arrays into a 2-D array.
Sample array: (10,20,30), (40,50,60)
Expected Output:
[[[10 40]]
[[20 50]]
[[30 60]]]

In [28]:
# The np.dstack() :This method is used to stack the two arrays in depth-wise along the third axis.
arr1 = np.array([[10], [20], [30]])
arr2 = np.array([[40], [50], [60]])
print('Array1: ', arr1)
print('Array2: ', arr2)

print('Depth stack: ', np.dstack((arr1, arr2)))

Array1:  [[10]
 [20]
 [30]]
Array2:  [[40]
 [50]
 [60]]
Depth stack:  [[[10 40]]

 [[20 50]]

 [[30 60]]]


49.Write a NumPy program to split an array of 14 elements into 3 arrays, each with 2, 4, and 8 elements in the original order.
Expected Output:
Original array: [ 1 2 3 4 5 6 7 8 9 10 11 12 13 14]
After splitting:
[array([1, 2]), array([3, 4, 5, 6]), array([ 7, 8, 9, 10, 11, 12, 13, 14])]

In [30]:
arr = np.arange(1, 15)
print('Original Array: ', arr)

# np.split(array, Positions) : This method is used to split the array at the specified positions.
np.split(arr, [2, 6])

Original Array:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]

50. Write  a NumPy program that splits an array of shape 4x4 into two arrays along the second axis.
Sample array :
[[ 0 1 2 3]
........
[12 13 14 15]]
Expected Output:
[array([[ 0, 1],
[ 4, 5],
[ 8, 9],
[12, 13]]), array([[ 2, 3],
[ 6, 7],
[10, 11],
[14, 15]]), array([], shape=(4, 0), dtype=int64)]

In [37]:
arr = np.arange(16).reshape(4, 4)
print('Original Array: ', arr)

# np.hsplit(array, positions) : This method is used to split the specified array in horizontally at specified positions
np.hsplit(arr, [2, 4])

Original Array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]),
 array([], shape=(4, 0), dtype=int32)]

51. Write a NumPy program to get the number of non-zero elements in an array.
Expected Output:
Original array:
[[ 0 10 20]
[20 30 40]]
Number of non zero elements in the above array:
5

In [38]:
arr = np.array([[0, 10, 20], [20, 30, 40]])
# np.count_nonzero(array) : This method counts the number of non-zero elements in the array specified.

print('Number of non zero elements in the array: ', np.count_nonzero(arr))

Number of non zero elements in the array:  5


52. Write a NumPy program to create a vector of size 10 with values ranging from 0 to 1, both excluded.
Expected Output:
[ 0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
0.63636364 0.72727273 0.81818182 0.90909091]

In [42]:
arr = np.linspace(0, 1, 12, endpoint=True)[1:-1]
print('Array: ', arr)

Array:  [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


53. Write a NumPy program (using numpy) to sum all the multiples of 3 or 5 below 100.
Sample array: 
[ 3 5 6 9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51 54
55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96   9]
2318

In [4]:
# By using Advance Indexing we can solve the problem
arr = np.arange(1, 100)

# The below code filters those elements which are multiples of 3 or 5
arr = arr[(arr % 3 == 0)|(arr % 5 == 0)]
print('Original Array: ', arr)

# np.sum(array) : This method return the sum of all elements in the array.
print('Sum of all Multiples: ', np.sum(arr))

Original Array:  [ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
Sum of all Multiples:  2318


54. Write a NumPy program to create and display every element of a NumPy array in Fortran order.
Expected Output:
Elements of the array in Fortan array:
0 4 8 1 5 9 2 6 10 3 7 11

In [6]:
arr = np.arange(12).reshape(3, 4)

# for Fortran order, just simply specify order='F' in np.nditer(array, order='F')
for i in np.nditer(arr, order='F'):
    print(i, end=' ')

0 4 8 1 5 9 2 6 10 3 7 11 

55. Write a NumPy program to create an array of (3, 4) shapes and convert the array elements into smaller chunks.

In [9]:
arr = np.arange(12).reshape(3, 4)

for i in np.nditer(arr, flags=['external_loop'], order='F'):
    print(i)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


56. Write a NumPy program to create a record array from a (flat) list of arrays.
Sample arrays: [1,2,3,4], ['Red', 'Green', 'White', 'Orange'], [12.20,15,20,40]
Expected Output:
(1, 'Red', 12.2)
(2, 'Green', 15.0)
(3, 'White', 20.0)

In [12]:
# np.core.records.fromarrays([array1, array2, array3, ....],names=[title1, title2, title3, ...]) : This method creates the records from the array elements.
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array(['Red', 'Green', 'White', 'Orange'])
arr3 = np.array([12.20, 15, 20, 40])

print(np.core.records.fromarrays([arr1, arr2, arr3], names=['X', 'Y', 'Z']))

[(1, 'Red', 12.2) (2, 'Green', 15. ) (3, 'White', 20. )
 (4, 'Orange', 40. )]


57. Write a NumPy program to convert a NumPy array into a Python list structure.
Expected Output:
Original array elements:
[[0 1]
[2 3]
[4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]

In [14]:
arr = np.array([[0, 1], [2, 3], [4, 5]])
print('Original Array Elements: ', arr)

# array.tolist() : This method converts the array to list.
print('Array to List: ',arr.tolist())

Original Array Elements:  [[0 1]
 [2 3]
 [4 5]]
Array to List:  [[0, 1], [2, 3], [4, 5]]


58. Write a NumPy program to access an array by column.

In [17]:
arr = np.arange(9).reshape(3, 3)
print('Original Array: ', arr)
# Using Advanced Indexing to access the array by column.
print('Col1: ',arr[:, 0])
print('Col2: ',arr[:, 1])
print('Col3: ',arr[:, 2])

Original Array:  [[0 1 2]
 [3 4 5]
 [6 7 8]]
Col1:  [0 3 6]
Col2:  [1 4 7]
Col3:  [2 5 8]


59. Write a NumPy program to convert a NumPy array of floating values to a numpy array of integer values.
Expected Output:
Original array elements:
[[ 12. 12.51]
[ 2.34 7.98]
[ 25.23 36.5 ]]
Convert float values to intger values:
[[12 12]
[ 2 7]
[25 36]]

In [19]:
# create the array
arr = np.array([[12. , 12.51], [2.34, 7.98], [25.23, 36.5]])
print('Original Array: ', arr)

# array.astype(int) : This method will convert the above floating point array to integer array.
print('Integer Array: ', arr.astype(int))

Original Array:  [[12.   12.51]
 [ 2.34  7.98]
 [25.23 36.5 ]]
Integer Array:  [[12 12]
 [ 2  7]
 [25 36]]


60. Write a NumPy program to create a NumPy array of 10 integers from a generator.

In [20]:
# np.fromiter(iterable, dtype) : this method generates an array from an iterable.
print(np.fromiter((i for i in range(10)), dtype='int'))

[0 1 2 3 4 5 6 7 8 9]


61. Write a NumPy program to add an extra column to a NumPy array.

Expected Output:
[[ 10 20 30 100]
[ 40 50 60 200]]

In [25]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
print('Original Array: ', arr)
arr2 = np.array([[100], [200]])
print('Array to append: ', arr2)

# np.append(array1, array2, axis) : This method will append the array2 to array1 in the specified axis. Here axis=1, for column wise appending
print('Appended Array: ', np.append(arr, arr2, axis=1))

Original Array:  [[10 20 30]
 [40 50 60]]
Array to append:  [[100]
 [200]]
Appended Array:  [[ 10  20  30 100]
 [ 40  50  60 200]]


62. Write a NumPy program to replace all elements of NumPy array that are greater than the specified array.

Expected Output:
Original array:
[[ 0.42436315 0.48558583 0.32924763]
[ 0.7439979 0.58220701 0.38213418]
[ 0.5097581 0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than. 5
[[ 0.42436315 0.48558583 0.32924763]
[ 0.5 0.5 0.38213418]
[ 0.5 0.34528799 0.1563123 ]]

In [29]:
arr = np.array([[0.42436315, 0.48558583, 0.32924763],[0.7439979, 0.58220701, 0.38213418],[0.5097581, 0.34528799, 0.1563123]])
print('Original Array: ', arr)

# we can use Advanced Indexing here..
arr[arr > .5] = .5
print('Replaced Array: ', arr)

Original Array:  [[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replaced Array:  [[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


63. Write a NumPy program to remove specific elements from a NumPy array.

Expected Output:
Original array:
[ 10 20 30 40 50 60 70 80 90 100]
Delete first, fourth and fifth elements:
[ 20 30 60 70 80 90 100]

In [32]:
arr = np.arange(10, 101, 10)
print('Original Array: ', arr)

# np.delete(array, index_list) : This method deletes those elements from the array specified which are in index_list
print('Removed Array: ', np.delete(arr, [0, 3, 4]))

Original Array:  [ 10  20  30  40  50  60  70  80  90 100]
Removed Array:  [ 20  30  60  70  80  90 100]


64. Write a NumPy program to select indices satisfying multiple conditions in a NumPy array.
Sample array :
a = np.array([97, 101, 105, 111, 117])
b = np.array(['a','e','i','o','u'])
Note: Select the elements from the second array corresponding to elements in the first array that are greater than 100 and less than 110
Expected Output:
Original arrays
[ 97 101 105 111 117]
['a' 'e' 'i' 'o' 'u']
Elements from the second array corresponding to elements in the first
array that are greater than 100 and less than 110:
['e' 'i']

In [40]:
arr1 = np.array([97, 101, 105, 111, 117])
arr2 = np.array(['a', 'e', 'i', 'o', 'u'])
print('Array1: ', arr1)
print('Array2: ', arr2)

# Using Advanced Indexing as done below: 
print('Corresponding elements: ',arr2[(arr1 > 100) & (arr1 < 110)])

Array1:  [ 97 101 105 111 117]
Array2:  ['a' 'e' 'i' 'o' 'u']
Corresponding elements:  ['e' 'i']


65. Write a NumPy program to get the magnitude of a vector in NumPy.
Expected Output:
Original array:
[1 2 3 4 5]
Magnitude of the vector:
7.4161984871

In [41]:
# Calculating the magnitude (L2 norm) of the vector 'x' using np.linalg.norm() function
arr = np.arange(1, 6)

# The L2 norm is the square root of the sum of the squared elements in the array.
magnitude = np.linalg.norm(arr)

print('Magnitude: ', magnitude)

Magnitude:  7.416198487095663


66. Write a NumPy program to count the frequency of distinct values in a NumPy array.
Expected Output:
Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
[ 3 4 2 2 1]]

In [46]:
arr = np.array([10, 10, 20, 10, 20, 20, 20, 30, 30, 50, 40, 40])
print('Original Array: ', arr)

# np.unique(array, return_count=True) : this method returns the unique elements and their count in the array
unique_elements, frequency = np.unique(arr, return_counts=True)

# np.asarray(tuple_of_arrays) : This method combines the arrays into a single array.
print('Frequency of unique values: ',np.asarray((unique_elements, frequency)))

Original Array:  [10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values:  [[10 20 30 40 50]
 [ 3  4  2  2  1]]


67. Write a NumPy program to divide each row by a vector element.
Expected Output:
Original array:
[[20 20 20]
[30 30 30]
[40 40 40]]
Vector:
[20 30 40]
[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]

In [49]:
arr = np.array([[20,20,20],[30,30,30],[40,40,40]])
print('Array: ', arr)
vector = np.array([20, 30, 40])
print('Vector: ', vector)

print(arr/vector[:, None])

Array:  [[20 20 20]
 [30 30 30]
 [40 40 40]]
Vector:  [20 30 40]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


68. Write a NumPy program to sum and compute the product of a numpy array of elements.
Expected Output:
Original array:
[ 10. 20. 30.]
Sum of the array elements:
60.0
Product of the array elements:
6000.0

In [50]:
arr = np.array([10.,20.,30.])
# np.sum(array) : Returns the sum of all the elements
# np.prod(array) : Returns the product of all the elements.
print('Array: ', arr)
print('Sum of the array elements: ', np.sum(arr))
print('Product of the array elements: ', np.prod(arr))

Array:  [10. 20. 30.]
Sum of the array elements:  60.0
Product of the array elements:  6000.0


69. Write a NumPy program to take values from a source array and put them at specified indices of another array.
Expected Output:
[ 10. 10. 20. 30. 30.]
Put 0 and 40 in first and fifth position of the above array
Array x after put two values: [ 0. 10. 20. 30. 40.]

In [53]:
arr = np.array([10, 10, 20, 30, 30])
print('Array: ', arr)
arr2 = np.array([0, 40])
print('Array to Replace: ', arr2)

# array1.put(indices, array2) : This method will replace the array2 values in array1 with the specified indices.
arr.put([0, 4], arr2)
print('Replaced Array: ', arr)

Array:  [10 10 20 30 30]
Array to Replace:  [ 0 40]
Replaced Array:  [ 0 10 20 30 40]


70. Write a NumPy program to access the last two columns of a multidimensional column. Original Array: [[1 2 3]
[4 5 6]
[7 8 9]]

In [5]:
arr = np.arange(1, 10).reshape(3, 3)
print('Original Array: ', arr)

# we can access last two cols using advanced indexing like done below.
print('Last Two cols: ', arr[:,1:])

Original Array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Last Two cols:  [[2 3]
 [5 6]
 [8 9]]


71. Write a NumPy program to count the occurrences of a specified item in a given NumPy array.:
Original array:
[10 20 20 20 20 0 20 30 30 30 0 0 20 20 0]

In [8]:
arr = np.array([10, 20, 20, 20, 20, 0, 20, 30, 30, 30, 0, 0, 20, 20, 0])
print('Original Array: ', arr)

# np.count_nonzero(array == item) : this method returns the count of an item in array.
print('Count of 10: ', np.count_nonzero(arr == 10))
print('Count of 20: ', np.count_nonzero(arr == 20))
print('Count of 30: ', np.count_nonzero(arr == 30))
print('Count of 0: ', np.count_nonzero(arr == 0))

Original Array:  [10 20 20 20 20  0 20 30 30 30  0  0 20 20  0]
Count of 10:  1
Count of 20:  7
Count of 30:  3
Count of 0:  4


72. Write a NumPy program to calculate percentiles for a sequence or single-dimensional NumPy array.


In [12]:
arr = np.arange(1, 6)
print('Array: ', arr)

# np.percentile(array, percentile_value) : This method returns the value obtained from array using percentile.
print('50 percentile: ', np.percentile(arr, 50))
print('22 percentile: ', np.percentile(arr, 22))
print('12 percentile: ', np.percentile(arr, 12))

Array:  [1 2 3 4 5]
50 percentile:  3.0
22 percentile:  1.88
12 percentile:  1.48


73. Write a NumPy program to find the indices of elements equal to zero in a NumPy array.
Sample Output:
Original array:
[1 0 2 0 3 0 4 5 6 7 8]
Indices of elements equal to zero of the said array:
[1 3 5]

In [15]:
arr = np.array([1, 0, 2, 0, 3, 0, 4, 5, 6, 7, 8])
print('Original Array: ', arr)

# np.where(condition) : This returns the indices of the elements which satisfy the condition.
print('Indices of zero elements: ', np.where(arr == 0)[0])

Original Array:  [1 0 2 0 3 0 4 5 6 7 8]
Indices of zero elements:  [1 3 5]
