In [1]:
# import numpy library with alias np
import numpy as np

1. Write a NumPy program to compute the multiplication of two given matrixes.


In [3]:
# np.dot(matrix1, matrix2) : This method returns a third matrix which is the product of the matrix1 and matrix2 which are passed as arguments.
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[1, 2], [3, 4]])
print('Matrix1: ', matrix1)
print('Matrix2: ', matrix2)

print('Matrix Multiplied: ', np.dot(matrix1, matrix2))

Matrix1:  [[1 2]
 [3 4]]
Matrix2:  [[1 2]
 [3 4]]
Matrix Multiplied:  [[ 7 10]
 [15 22]]


2. Write a NumPy program to compute the outer product of two given vectors.


In [4]:
# Outer Product : It is the product between the elements of a cartesian product. e.g. let a = [1,2] and b = [3, 4]. Therefore the cartesian products are
#                 (1, 3), (1, 4), (2, 3), (2, 4). Now the outer products are: 3, 4, 6, 8 ( since 1*3, 1*4, 2*3, 2*4 respectively).

# np.outer(array1, array2) : this method creates the outer product between the two arrays that are passed as arguments.
vector1 = np.array([1, 2])
vector2 = np.array([3, 4])
print('Vector1: ', vector1)
print('Vectro2: ', vector2)

print('Outer Product: ', np.outer(vector1, vector2))

Vector1:  [1 2]
Vectro2:  [3 4]
Outer Product:  [[3 4]
 [6 8]]


3. Write a NumPy program to compute the cross product of two given vectors.


In [6]:
# Cross Product: It is that one which we use in physics, where we get magnitude and direction. Negative sign indicates opposite direction.

# np.cross(array1, array2) : This method generates the cross product of the two arrays that we pass as argument

arr1 = np.arange(4).reshape(2, 2)
arr2 = np.arange(4, 8).reshape(2, 2)
print('Array1: ', arr1)
print('Array2: ', arr2)

print('Cross Product: ', np.cross(arr1, arr2))

Array1:  [[0 1]
 [2 3]]
Array2:  [[4 5]
 [6 7]]
Cross Product:  [-4 -4]


4. Write a NumPy program to compute the determinant of a given square array.


In [10]:
# np.linalg.det(matrix) : This method returns the determinant of a square matrix.
# np.linalg : This module is used to solve linear algebra problems..
square_matrix = np.arange(4).reshape(2, 2)
print('Square Matrix: ', square_matrix)

print('Determinant: ', np.linalg.det(square_matrix))

Square Matrix:  [[0 1]
 [2 3]]
Determinant:  -2.0


5. Write a NumPy program to compute the inner product of vectors for 1-D arrays (without complex conjugation) and in higher dimension.

In [11]:
# Inner Product: It is the sum of zip products generated with the two arrays. e.g. a = [1, 4, 6] and b = [2, 4, 8] are two ndarray. The zips are
#                (1, 2), (4, 4) and (6, 8), when we take sum of zip products we get: 2 + 16 + 48 = 66.
# np.inner(array1, array2) : This will give the inner product.
arr1 = np.array([1, 4, 6])
arr2 = np.array([2, 4, 8])
print('Array1: ', arr1)
print('Array2: ', arr2)

print('Inner Product: ', np.inner(arr1, arr2))

Array1:  [1 4 6]
Array2:  [2 4 8]
Inner Product:  66


6. Write a NumPy program to compute the eigenvalues and right eigenvectors of a given square array.


In [12]:
# np.linalg.eig(matrix) : This method generates the eigen value and eigen vector.
matrix = np.arange(1, 17).reshape(4, 4)
print('Matrix: ', matrix)

eigen_value, eigen_vector = np.linalg.eig(matrix)
print('Eigen Values: ', eigen_value)
print('Eigen Vectors: ', eigen_vector)

Matrix:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Eigen Values:  [ 3.62093727e+01 -2.20937271e+00 -2.57831463e-15  5.57979826e-17]
Eigen Vectors:  [[-0.15115432  0.72704996  0.51747505 -0.06588506]
 [-0.34923733  0.28320876 -0.82375673 -0.31743721]
 [-0.54732033 -0.16063243  0.09508831  0.83252961]
 [-0.74540333 -0.60447363  0.21119337 -0.44920733]]


7. Write a NumPy program to compute the condition number of a given matrix.


In [13]:
# Condition Number :  The condition number of a function with respect to an argument measures how much the output value of the function can change
#                     for a small change in the input argument. This is used to measure how sensitive a function is to changes or errors in the input, 
#                     and how much error in the output results from an error in the input.In linear regression the condition number can be used as a 
#                     diagnostic for multicollinearity.

# np.linalg.cond(matrix) : This will return the condition number of the matrix.

matrix = np.arange(16).reshape(4, 4)
print('Matrix: ', matrix)

print('Condition Number of the Matrix: ', np.linalg.cond(matrix))

Matrix:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Condition Number of the Matrix:  8.942064346927267e+17


8. Write a NumPy program to find a matrix or vector norm.


In [15]:
# L2 Norm : It is the squareroot of sum of squares of each element in the vector or matrix.
# np.linalg.norm(array) : This returns the l2 norm of the given array.

matrix = np.arange(9).reshape(3, 3)
vector = np.arange(9)
print('Vector: ', vector)
print('Matrix: ', matrix)

print('Vector norm: ', np.linalg.norm(vector))
print('Matrix norm: ', np.linalg.norm(matrix))

Vector:  [0 1 2 3 4 5 6 7 8]
Matrix:  [[0 1 2]
 [3 4 5]
 [6 7 8]]
Vector norm:  14.2828568570857
Matrix norm:  14.2828568570857


9. Write a NumPy program to compute the inverse of a given matrix.


In [17]:
# np.linalg.inv(array) : This method returns the inverse of the passed array.
arr = np.arange(1, 5).reshape(2, 2)
print('Array: ', arr)

print('Inverse of the Array: ', np.linalg.inv(arr))

Array:  [[1 2]
 [3 4]]
Inverse of the Array:  [[-2.   1. ]
 [ 1.5 -0.5]]


10. Write a NumPy program to calculate the QR decomposition of a given matrix.


In [24]:
# QR decomposition : let say we have a Matrix A. Then we can decompose A into the product of two other matrice Q and R, where Q is an orthogonal matrix
#                    and R is an upper triangular matrix. Therefor A = QR. For more details see the below output of the example.

# np.linalg.qr(Matrix) : This method generates two other matrices Q and R.

matrix = np.arange(16).reshape(4, 4)
print('Original Matrix: ', matrix)

print('\nQR Decomposition of the matrix: ')
print('\nQ matrix: ', np.linalg.qr(matrix)[0])
print('\nR matrix: ', np.linalg.qr(matrix)[1])

Original Matrix:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

QR Decomposition of the matrix: 

Q matrix:  [[ 0.         -0.83666003  0.48308786  0.25812035]
 [-0.26726124 -0.47809144 -0.8365087   0.01591196]
 [-0.53452248 -0.11952286  0.22375381 -0.80618499]
 [-0.80178373  0.23904572  0.12966702  0.53215267]]

R matrix:  [[-1.49666295e+01 -1.65701970e+01 -1.81737645e+01 -1.97773319e+01]
 [ 0.00000000e+00 -1.19522861e+00 -2.39045722e+00 -3.58568583e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.71941189e-15 -5.80877984e-15]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -9.19619468e-16]]


11. Write a NumPy program to compute the sum of the diagonal element of a given array.


In [25]:
# trace(matrix) : This is the sum of diagonal elements in a matrix.
# np.trace(matrix) : This method is used to find the trace of the matrix.

matrix = np.arange(16).reshape(4, 4)
print('Matrix: ', matrix)

print('\nTrace of the Matrix: ', np.trace(matrix))

Matrix:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Trace of the Matrix:  30
